CREATE VIEW export_occasions_view 
AS
SELECT 'anniversary' AS 'entity_key', 'Anniversary' AS 'name'
UNION ALL SELECT 'anniversary_anniversary_1_year_working_from_home_work_anniversary', 'Anniversary - Anniversary 1 year working from home - Work anniversary'
UNION ALL SELECT 'anniversary_work_anniversary', 'Anniversary - Work anniversary'
UNION ALL SELECT 'aoc_think', 'AOC think'
UNION ALL SELECT 'baby_party_invitations', 'Baby party (invitations)'
UNION ALL SELECT 'baby_shower_invitations', 'Baby shower (invitations)'
UNION ALL SELECT 'bachelor_party_invitations', 'Bachelor party (invitations)'
UNION ALL SELECT 'back_to_school_cards', 'Back to school cards'
UNION ALL SELECT 'back_to_school_cards_highschool', 'Back to school cards - Highschool'
UNION ALL SELECT 'back_to_school_cards_highschool_new_schoolyear', 'Back to school cards - Highschool - New schoolyear'
UNION ALL SELECT 'back_to_school_cards_new_schoolyear', 'Back to school cards - New schoolyear'
UNION ALL SELECT 'baptism_and_communion_invitations', 'Baptism and communion (invitations)'
UNION ALL SELECT 'birth', 'Birth'
UNION ALL SELECT 'birth_birth_premature', 'Birth - Birth premature'
UNION ALL SELECT 'birth_birth_rainbow_child', 'Birth - Birth rainbow child'
UNION ALL SELECT 'birth_birth_with_handicap', 'Birth - Birth with handicap'
UNION ALL SELECT 'birth_cards_birth', 'Birth cards (Birth)'
UNION ALL SELECT 'birth_cards_birth_birth_cards_boy', 'Birth cards (Birth) - Birth cards (boy)'
UNION ALL SELECT 'birthday', 'Birthday'
UNION ALL SELECT 'birthday_birthday_belated_wishes', 'Birthday - Birthday belated Wishes'
UNION ALL SELECT 'birthday_birthday_from_distance', 'Birthday - Birthday from distance'
UNION ALL SELECT 'birthday_birthday_in_dialect', 'Birthday - Birthday in dialect'
UNION ALL SELECT 'birthday_birthday_leap_year', 'Birthday - Birthday leap year'
UNION ALL SELECT 'birthday_birthday_with_age', 'Birthday - Birthday with age'
UNION ALL SELECT 'birthday_birthday_with_star_sign', 'Birthday - Birthday with star sign'
UNION ALL SELECT 'birthday_invitation_invitations', 'Birthday invitation (invitations)'
UNION ALL SELECT 'birthday_invitation_invitations_16_years', 'Birthday invitation (invitations) - 16 years'
UNION ALL SELECT 'birthday_invitation_invitations_18_years', 'Birthday invitation (invitations) - 18 years'
UNION ALL SELECT 'birthday_invitation_invitations_21_years', 'Birthday invitation (invitations) - 21 years'
UNION ALL SELECT 'birthday_invitation_invitations_25_years', 'Birthday invitation (invitations) - 25 years'
UNION ALL SELECT 'birthday_invitation_invitations_30_years', 'Birthday invitation (invitations) - 30 years'
UNION ALL SELECT 'birthday_invitation_invitations_40_years', 'Birthday invitation (invitations) - 40 years'
UNION ALL SELECT 'birthday_invitation_invitations_50_years', 'Birthday invitation (invitations) - 50 years'
UNION ALL SELECT 'birthday_invitation_invitations_60_years', 'Birthday invitation (invitations) - 60 years'
UNION ALL SELECT 'birthday_invitation_invitations_70_years', 'Birthday invitation (invitations) - 70 years'
UNION ALL SELECT 'birthday_invitation_invitations_age_invitations', 'Birthday invitation (invitations) - Age invitations'
UNION ALL SELECT 'birthday_invitation_invitations_age_invitations_21_years', 'Birthday invitation (invitations) - Age invitations - 21 years'
UNION ALL SELECT 'birthday_invitation_invitations_age_invitations_25_years', 'Birthday invitation (invitations) - Age invitations - 25 years'
UNION ALL SELECT 'birthday_invitation_invitations_age_invitations_30_years', 'Birthday invitation (invitations) - Age invitations - 30 years'
UNION ALL SELECT 'birthday_invitation_invitations_age_invitations_40_years', 'Birthday invitation (invitations) - Age invitations - 40 years'
UNION ALL SELECT 'birthday_invitation_invitations_age_invitations_50_years', 'Birthday invitation (invitations) - Age invitations - 50 years'
UNION ALL SELECT 'birthday_invitation_invitations_age_invitations_60_years', 'Birthday invitation (invitations) - Age invitations - 60 years'
UNION ALL SELECT 'birthday_invitation_invitations_age_invitations_70_years', 'Birthday invitation (invitations) - Age invitations - 70 years'
UNION ALL SELECT 'birthday_invitation_invitations_age_invitations_80_years', 'Birthday invitation (invitations) - Age invitations - 80 years'
UNION ALL SELECT 'birthday_invitation_invitations_age_invitations_changeable_age', 'Birthday invitation (invitations) - Age invitations - Changeable age'
UNION ALL SELECT 'birthday_invitation_invitations_age_invitations_changeable_age_30_years', 'Birthday invitation (invitations) - Age invitations - Changeable age - 30 years'
UNION ALL SELECT 'birthday_invitation_invitations_age_invitations_changeable_age_50_years', 'Birthday invitation (invitations) - Age invitations - Changeable age - 50 years'
UNION ALL SELECT 'birthday_invitation_invitations_changeable_age', 'Birthday invitation (invitations) - Changeable age'
UNION ALL SELECT 'birthday_invitation_invitations_changeable_age_16_years', 'Birthday invitation (invitations) - Changeable age - 16 years'
UNION ALL SELECT 'birthday_invitation_invitations_changeable_age_21_years', 'Birthday invitation (invitations) - Changeable age - 21 years'
UNION ALL SELECT 'birthday_invitation_invitations_changeable_age_25_years', 'Birthday invitation (invitations) - Changeable age - 25 years'
UNION ALL SELECT 'birthday_invitation_invitations_changeable_age_30_years', 'Birthday invitation (invitations) - Changeable age - 30 years'
UNION ALL SELECT 'birthday_invitation_invitations_changeable_age_age_invitations', 'Birthday invitation (invitations) - Changeable age - Age invitations'
UNION ALL SELECT 'birthday_invitation_invitations_changeable_age_age_invitations_21_years', 'Birthday invitation (invitations) - Changeable age - Age invitations - 21 years'
UNION ALL SELECT 'birthday_invitation_invitations_changeable_age_age_invitations_40_years', 'Birthday invitation (invitations) - Changeable age - Age invitations - 40 years'
UNION ALL SELECT 'birthday_invitation_invitations_changeable_age_age_invitations_50_years', 'Birthday invitation (invitations) - Changeable age - Age invitations - 50 years'
UNION ALL SELECT 'birthday_invitation_invitations_surprise_party', 'Birthday invitation (invitations) - Surprise party'
UNION ALL SELECT 'blue_monday', 'Blue Monday'
UNION ALL SELECT 'brother_and_sister_day', 'Brother and Sister day'
UNION ALL SELECT 'business_invitations_invitations', 'Business invitations (invitations)'
UNION ALL SELECT 'carnaval', 'Carnaval'
UNION ALL SELECT 'childrens_party_invitations', 'Childrens party (invitations)'
UNION ALL SELECT 'childrens_party_invitations_changeable_age_kids', 'Childrens party (invitations) - Changeable age kids'
UNION ALL SELECT 'childrens_party_invitations_first_childrensbirthday', 'Childrens party (invitations) - First childrensbirthday'
UNION ALL SELECT 'chinese_new_year', 'Chinese New Year'
UNION ALL SELECT 'christmas', 'Christmas'
UNION ALL SELECT 'christmas_christmas_birth', 'Christmas - Christmas birth'
UNION ALL SELECT 'christmas_christmas_birthday', 'Christmas - Christmas birthday'
UNION ALL SELECT 'christmas_christmas_humor', 'Christmas - Christmas humor'
UNION ALL SELECT 'christmas_christmas_in_the_weekend', 'Christmas - Christmas in the weekend'
UNION ALL SELECT 'christmas_christmas_in_the_weekend_christmas_humor_christmas_most_sold', 'Christmas - Christmas in the weekend - Christmas humor - Christmas most sold'
UNION ALL SELECT 'christmas_christmas_most_sold', 'Christmas - Christmas most sold'
UNION ALL SELECT 'christmas_christmas_most_sold_christmas_humor', 'Christmas - Christmas most sold - Christmas humor'
UNION ALL SELECT 'christmas_christmas_most_sold_christmas_thinking_of_you', 'Christmas - Christmas most sold - Christmas thinking of you'
UNION ALL SELECT 'christmas_christmas_new_home', 'Christmas - Christmas new home'
UNION ALL SELECT 'christmas_christmas_thank_you', 'Christmas - Christmas thank you'
UNION ALL SELECT 'christmas_christmas_thinking_of_you', 'Christmas - Christmas thinking of you'
UNION ALL SELECT 'christmas_christmas_thinking_of_you_christmas_most_sold', 'Christmas - Christmas thinking of you - Christmas most sold'
UNION ALL SELECT 'christmas_invitations', 'Christmas (invitations)'
UNION ALL SELECT 'christmas_invitations_christmas_business_ia', 'Christmas (invitations) - Christmas Business (IA)'
UNION ALL SELECT 'christmas_newyear_cards', 'Christmas - NewYear (cards)'
UNION ALL SELECT 'communion', 'Communion'
UNION ALL SELECT 'condolence', 'Condolence'
UNION ALL SELECT 'condolence_condolence_pet', 'Condolence - Condolence pet'
UNION ALL SELECT 'condolence_condolence_with_text', 'Condolence - Condolence with text'
UNION ALL SELECT 'condolence_condolence_without_text', 'Condolence - Condolence without text'
UNION ALL SELECT 'condolence_yearday', 'Condolence - Yearday'
UNION ALL SELECT 'confirmation', 'Confirmation'
UNION ALL SELECT 'congratulations_card_and_gift', 'Congratulations (card and gift)'
UNION ALL SELECT 'day_of_caregiving', 'Day of caregiving'
UNION ALL SELECT 'day_of_the_animals', 'Day of the animals'
UNION ALL SELECT 'dinner_party_en_drinks_invitations', 'Dinner party en drinks (invitations)'
UNION ALL SELECT 'dinner_party_en_drinks_invitations_borrel_invitation', 'Dinner party en drinks (invitations) - Borrel (invitation)'
UNION ALL SELECT 'easter_pasen', 'Easter/Pasen'
UNION ALL SELECT 'eid_al_adha_>_offerfeest', 'Eid al Adha > Offerfeest'
UNION ALL SELECT 'eid_mubarak__suikerfeest', 'Eid Mubarak * Suikerfeest'
UNION ALL SELECT 'exam_party_invitations', 'Exam party (invitations)'
UNION ALL SELECT 'failed', 'Failed'
UNION ALL SELECT 'failed_re_exam', 'Failed - re exam'
UNION ALL SELECT 'fathersday', 'Fathersday'
UNION ALL SELECT 'fathersday_fathersday_beercards', 'Fathersday - Fathersday beercards'
UNION ALL SELECT 'fathersday_fathersday_best_sold', 'Fathersday - Fathersday best sold'
UNION ALL SELECT 'fathersday_fathersday_best_sold_fathersday_thinking_of_you', 'Fathersday - Fathersday best sold - Fathersday thinking of you'
UNION ALL SELECT 'fathersday_fathersday_thinking_of_you', 'Fathersday - Fathersday thinking of you'
UNION ALL SELECT 'fathersday_fathersday_thinking_of_you_fathersday_best_sold', 'Fathersday - Fathersday thinking of you - Fathersday best sold'
UNION ALL SELECT 'fathersday_first_fathers_day', 'Fathersday - First Fathers day'
UNION ALL SELECT 'four_days_marches', 'Four days marches'
UNION ALL SELECT 'friendship2', 'Friendship2'
UNION ALL SELECT 'garden_party_invitations', 'Garden party (invitations)'
UNION ALL SELECT 'gender_reveal_party_invitations', 'Gender reveal party (invitations)'
UNION ALL SELECT 'get_well', 'Get well'
UNION ALL SELECT 'get_well_broken_bones', 'Get well - Broken bones'
UNION ALL SELECT 'get_well_chronically_or_seriously_ill', 'Get well - Chronically or seriously ill'
UNION ALL SELECT 'get_well_get_well_welcome_home', 'Get well - Get well welcome home'
UNION ALL SELECT 'good_luck', 'Good luck'
UNION ALL SELECT 'graduation', 'Graduation'
UNION ALL SELECT 'graduation_boat_license', 'Graduation - boat license'
UNION ALL SELECT 'graduation_course_completed', 'Graduation - Course completed'
UNION ALL SELECT 'graduation_driving_license_extended', 'Graduation - Driving License extended'
UNION ALL SELECT 'graduation_driving_license_extended_driving_license_graduated', 'Graduation - Driving License extended - Driving License graduated'
UNION ALL SELECT 'graduation_driving_license_graduated', 'Graduation - Driving License graduated'
UNION ALL SELECT 'graduation_driving_license_graduated_graduated_high_school', 'Graduation - Driving License graduated - Graduated high school'
UNION ALL SELECT 'graduation_graduated_afgestudeerd', 'Graduation - Graduated afgestudeerd'
UNION ALL SELECT 'graduation_graduated_high_school', 'Graduation - Graduated high school'
UNION ALL SELECT 'graduation_graduated_high_school_driving_license_graduated', 'Graduation - Graduated high school - Driving License graduated'
UNION ALL SELECT 'graduation_graduated_propaedeutic_certificate', 'Graduation - Graduated Propaedeutic certificate'
UNION ALL SELECT 'grandparents_day', 'Grandparents day'
UNION ALL SELECT 'halloween', 'Halloween'
UNION ALL SELECT 'hanukkah', 'Hanukkah'
UNION ALL SELECT 'happy_pride', 'Happy Pride'
UNION ALL SELECT 'housewarming_invitations_cardhouse', 'Housewarming (invitations Cardhouse)'
UNION ALL SELECT 'international_boss_day', 'International boss day'
UNION ALL SELECT 'international_womens_day', 'International Womens Day'
UNION ALL SELECT 'just_because', 'Just because'
UNION ALL SELECT 'just_because_beautiful_moments', 'Just because - Beautiful moments'
UNION ALL SELECT 'kingsday', 'Kingsday'
UNION ALL SELECT 'kingsday_kingsday_birthday', 'Kingsday - Kingsday birthday'
UNION ALL SELECT 'love', 'Love'
UNION ALL SELECT 'love_anniversary_relationship', 'Love - Anniversary relationship'
UNION ALL SELECT 'marriage_anniversary_invitations', 'Marriage anniversary (invitations)'
UNION ALL SELECT 'marriage_anniversary_invitations_change_number', 'Marriage anniversary (invitations) - Change number'
UNION ALL SELECT 'marriage_anniversary_invitations_change_number_married_10_years', 'Marriage anniversary (invitations) - Change number - married 10 years'
UNION ALL SELECT 'marriage_anniversary_invitations_change_number_married_25_years', 'Marriage anniversary (invitations) - Change number - married 25 years'
UNION ALL SELECT 'marriage_anniversary_invitations_change_number_married_40_years', 'Marriage anniversary (invitations) - Change number - married 40 years'
UNION ALL SELECT 'marriage_anniversary_invitations_change_number_married_5_years', 'Marriage anniversary (invitations) - Change number - married 5 years'
UNION ALL SELECT 'marriage_anniversary_invitations_change_number_married_50_years', 'Marriage anniversary (invitations) - Change number - married 50 years'
UNION ALL SELECT 'marriage_anniversary_invitations_married_10_years', 'Marriage anniversary (invitations) - married 10 years'
UNION ALL SELECT 'marriage_anniversary_invitations_married_12.5_years', 'Marriage anniversary (invitations) - married 12.5 years'
UNION ALL SELECT 'marriage_anniversary_invitations_married_25_years', 'Marriage anniversary (invitations) - married 25 years'
UNION ALL SELECT 'marriage_anniversary_invitations_married_30_years', 'Marriage anniversary (invitations) - married 30 years'
UNION ALL SELECT 'marriage_anniversary_invitations_married_35_years', 'Marriage anniversary (invitations) - married 35 years'
UNION ALL SELECT 'marriage_anniversary_invitations_married_40_years', 'Marriage anniversary (invitations) - married 40 years'
UNION ALL SELECT 'marriage_anniversary_invitations_married_50_years', 'Marriage anniversary (invitations) - married 50 years'
UNION ALL SELECT 'milestones', 'Milestones'
UNION ALL SELECT 'mothersday', 'Mothersday'
UNION ALL SELECT 'mothersday_first_mothersday', 'Mothersday - First mothersday'
UNION ALL SELECT 'mothersday_mothersday_best_sold', 'Mothersday - Mothersday best sold'
UNION ALL SELECT 'mothersday_mothersday_distance', 'Mothersday - Mothersday distance'
UNION ALL SELECT 'mothersday_mothersday_thinking_of_you', 'Mothersday - Mothersday thinking of you'
UNION ALL SELECT 'moving_announcement__invitations', 'Moving announcement (invitations)'
UNION ALL SELECT 'moving_announcement__invitations_housewarming_invitations', 'Moving announcement (invitations) - Housewarming (invitations)'
UNION ALL SELECT 'moving_announcement__invitations_moving_announcement_christmas', 'Moving announcement (invitations) - Moving announcement christmas'
UNION ALL SELECT 'moving_announcement__invitations_moving_invitations', 'Moving announcement (invitations) - Moving (invitations)'
UNION ALL SELECT 'new_home', 'New home'
UNION ALL SELECT 'new_home_living_together', 'New home - Living together'
UNION ALL SELECT 'new_home_renovate', 'New home - Renovate'
UNION ALL SELECT 'new_job', 'New Job'
UNION ALL SELECT 'new_job_say_goodbye', 'New Job - Say goodbye'
UNION ALL SELECT 'new_job_to_welcome', 'New Job - To welcome'
UNION ALL SELECT 'new_year_party_invitations_cardhouse', 'New year party (invitations cardhouse)'
UNION ALL SELECT 'new_years_party_invitations', 'New Years Party (invitations)'
UNION ALL SELECT 'new_years_party_invitations_new_years_reception_business', 'New Years Party (invitations) - New Years reception business'
UNION ALL SELECT 'opening_new_business', 'Opening new business'
UNION ALL SELECT 'opening_new_business_invitations', 'Opening new business (invitations)'
UNION ALL SELECT 'partnerships', 'Partnerships'
UNION ALL SELECT 'photoself', 'photoself'
UNION ALL SELECT 'pregnant', 'Pregnant'
UNION ALL SELECT 'pregnant_adoption', 'Pregnant - Adoption'
UNION ALL SELECT 'pregnant_extra_special', 'Pregnant - Extra special'
UNION ALL SELECT 'pregnant_maternity_leave', 'Pregnant - Maternity Leave'
UNION ALL SELECT 'pregnant_miscarriage', 'Pregnant - Miscarriage'
UNION ALL SELECT 'promotion_grandparentsday', 'Promotion Grandparentsday'
UNION ALL SELECT 'proud_of_you', 'Proud of you'
UNION ALL SELECT 'retirement', 'Retirement'
UNION ALL SELECT 'save_the_date_wedding_cards_only', 'Save the date (Wedding cards only)'
UNION ALL SELECT 'secretaryday', 'Secretaryday'
UNION ALL SELECT 'sinterklaas', 'Sinterklaas'
UNION ALL SELECT 'sorry', 'Sorry'
UNION ALL SELECT 'swimming_diploma', 'Swimming diploma'
UNION ALL SELECT 'thank_you', 'Thank you'
UNION ALL SELECT 'thank_you_cards_invitations', 'Thank you cards (invitations)'
UNION ALL SELECT 'thank_you_thank_you_caretakers', 'Thank you - Thank you caretakers'
UNION ALL SELECT 'thank_you_thank_you_teacher', 'Thank you - Thank you teacher'
UNION ALL SELECT 'thanksgiving', 'Thanksgiving'
UNION ALL SELECT 'thinking_of_you', 'Thinking of you'
UNION ALL SELECT 'vacation', 'Vacation'
UNION ALL SELECT 'vacation_greetings_from', 'Vacation - Greetings from'
UNION ALL SELECT 'vacation_honeymoon', 'Vacation - Honeymoon'
UNION ALL SELECT 'vacation_summer_pictures', 'Vacation - Summer pictures'
UNION ALL SELECT 'vacation_travelling', 'Vacation - Travelling'
UNION ALL SELECT 'vacation_vacation_welcome_home', 'Vacation - Vacation welcome home'
UNION ALL SELECT 'valentine', 'Valentine'
UNION ALL SELECT 'valentine_valentine_best_sold', 'Valentine - Valentine best sold'
UNION ALL SELECT 'valentine_valentine_best_sold_valentine_in_love', 'Valentine - Valentine best sold - Valentine In love'
UNION ALL SELECT 'valentine_valentine_best_sold_valentine_loving', 'Valentine - Valentine best sold - Valentine loving'
UNION ALL SELECT 'valentine_valentine_best_sold_valentine_online_dating', 'Valentine - Valentine best sold - Valentine online dating'
UNION ALL SELECT 'valentine_valentine_best_sold_valentine_single', 'Valentine - Valentine best sold - Valentine single'
UNION ALL SELECT 'valentine_valentine_best_sold_valentine_thinking_of_you', 'Valentine - Valentine best sold - Valentine thinking of you'
UNION ALL SELECT 'valentine_valentine_in_love', 'Valentine - Valentine In love'
UNION ALL SELECT 'valentine_valentine_in_love_valentine_best_sold', 'Valentine - Valentine In love - Valentine best sold'
UNION ALL SELECT 'valentine_valentine_in_love_valentine_loving', 'Valentine - Valentine In love - Valentine loving'
UNION ALL SELECT 'valentine_valentine_loving', 'Valentine - Valentine loving'
UNION ALL SELECT 'valentine_valentine_loving_valentine_best_sold', 'Valentine - Valentine loving - Valentine best sold'
UNION ALL SELECT 'valentine_valentine_loving_valentine_in_love', 'Valentine - Valentine loving - Valentine In love'
UNION ALL SELECT 'valentine_valentine_online_dating', 'Valentine - Valentine online dating'
UNION ALL SELECT 'valentine_valentine_online_dating_valentine_best_sold', 'Valentine - Valentine online dating - Valentine best sold'
UNION ALL SELECT 'valentine_valentine_secret_love', 'Valentine - Valentine secret love'
UNION ALL SELECT 'valentine_valentine_secret_love_valentine_best_sold', 'Valentine - Valentine secret love - Valentine best sold'
UNION ALL SELECT 'valentine_valentine_single', 'Valentine - Valentine single'
UNION ALL SELECT 'valentine_valentine_single_valentine_best_sold', 'Valentine - Valentine single - Valentine best sold'
UNION ALL SELECT 'valentine_valentine_thinking_of_you', 'Valentine - Valentine thinking of you'
UNION ALL SELECT 'valentine_valentine_thinking_of_you_valentine_best_sold', 'Valentine - Valentine thinking of you - Valentine best sold'
UNION ALL SELECT 'wedding', 'Wedding'
UNION ALL SELECT 'wedding_divorce', 'Wedding - Divorce'
UNION ALL SELECT 'wedding_engaged', 'Wedding - Engaged'
UNION ALL SELECT 'wedding_engaged_just_married_wedding_anniversary', 'Wedding - Engaged - Just Married - Wedding Anniversary'
UNION ALL SELECT 'wedding_gay_marriage', 'Wedding - Gay marriage'
UNION ALL SELECT 'wedding_invitation_wedding', 'Wedding invitation (Wedding)'
UNION ALL SELECT 'wedding_invitation_wedding_save_our_date', 'Wedding invitation (Wedding) - Save our date'
UNION ALL SELECT 'wedding_just_married', 'Wedding - Just Married'
UNION ALL SELECT 'wedding_just_married_wedding_anniversary', 'Wedding - Just Married - Wedding Anniversary'
UNION ALL SELECT 'wedding_notice_of_marriage', 'Wedding - Notice of marriage'
UNION ALL SELECT 'wedding_registered_partnership', 'Wedding - Registered partnership'
UNION ALL SELECT 'wedding_wedding_anniversary', 'Wedding - Wedding Anniversary'
UNION ALL SELECT 'wedding_witness', 'Wedding - Witness'
