CREATE OR REPLACE VIEW export_brands_view 
AS
SELECT 'beauty_cadeau' AS entity_key, 'Beauty cadeau' AS 'name'
UNION ALL SELECT 'bijenkorf', 'Bijenkorf'
UNION ALL SELECT 'bol_com', 'Bol.com'
UNION ALL SELECT 'de_nederlandse_sauna', 'De Nederlandse Sauna'
UNION ALL SELECT 'gift_for_you', 'Gift for you'
UNION ALL SELECT 'greetz', 'Greetz'
UNION ALL SELECT 'hema', 'Hema'
UNION ALL SELECT 'huis_en_tuin_cadeau', 'Huis en tuin cadeau'
UNION ALL SELECT 'intratuin', 'Intratuin'
UNION ALL SELECT 'karwei', 'Karwei'
UNION ALL SELECT 'kids_cadeau', 'Kids cadeau'
UNION ALL SELECT 'klus_cadeau', 'Klus Cadeau'
UNION ALL SELECT 'momento', 'Momento'
UNION ALL SELECT 'pathe', 'Pathe'
UNION ALL SELECT 'restaurant_cadeau', 'Restaurant cadeau'
UNION ALL SELECT 'vvv', 'VVV'
UNION ALL SELECT 'wellness', 'Wellness'
UNION ALL SELECT 'wonderbox', 'Wonderbox'
UNION ALL SELECT 'zalando', 'Zalando'
