CREATE OR REPLACE VIEW export_productranges_view 
AS
SELECT 'range-abacus-cards' AS entity_key, 'Abacus Cards' AS 'name', 'Abacus Cards' AS channel_key
UNION ALL SELECT 'range-alex-sharp-photography', 'Alex Sharp Photography', 'Alex Sharp'
UNION ALL SELECT 'range-all-the-best', 'All the best', 'All the Best Cards'
UNION ALL SELECT 'range-gift-delivery', 'Gift Delivery', 'All Things Banter'
UNION ALL SELECT 'range-idrew', 'Idrew', 'Andrew Thornton'
UNION ALL SELECT 'range-angela-chick', 'Angela Chick', 'Angela Chick'
UNION ALL SELECT 'range-anoela-cards', 'Anoela cards', 'Anoela Cards'
UNION ALL SELECT 'range-banter-king', 'Banter king', 'Banter King'
UNION ALL SELECT 'range-beth-fletcher-illustration', 'Beth Fletcher Illustration', 'Beth Fletcher Illustration'
UNION ALL SELECT 'range-blond-amsterdam-regular', 'Blond Amsterdam - regular', 'Blond Amsterdam'
UNION ALL SELECT 'range-blond-amsterdam-xmas--i-and-a', 'Blond Amsterdam - xmas / I&A', 'Blond Amsterdam'
UNION ALL SELECT 'range-blond-x-noir-regular', 'Blond x Noir - regular', 'Blond Amsterdam'
UNION ALL SELECT 'range-bold-and-bright', 'Bold and Bright', 'Bold and Bright'
UNION ALL SELECT 'range-bouffants-and-broken-hearts', 'Bouffants and Broken Hearts', 'Bouffants and Broken Hearts'
UNION ALL SELECT 'range-brainbox-candy', 'Brainbox candy', 'Brainbox Candy'
UNION ALL SELECT 'range-bright-spot-regular', 'Bright Spot - regular', 'Bright Spot'
UNION ALL SELECT 'range-bright-spot-xmas--i-and-a', 'Bright Spot - xmas / I&A', 'Bright Spot'
UNION ALL SELECT 'range-hotchpotch-skiseason-regular', 'Hotchpotch - Skiseason - regular', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-swan-lake-regular', 'Hotchpotch - Swan lake - regular', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-swan-lake-xmas--i-and-a', 'Hotchpotch - Swan lake - xmas / I&A', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-twelve-days-regular', 'Hotchpotch - Twelve days - regular', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-birthday-suit-regular', 'HotchPotch Birthday Suit - regular', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-charcoal-regular', 'HotchPotch Charcoal - regular', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-fiesta-regular', 'HotchPotch Fiesta - regular', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-frida-regular', 'HotchPotch Frida - regular', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-geewhiz-regular', 'HotchPotch GeeWhiz - regular', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-hello-neon-regular', 'HotchPotch Hello Neon - regular', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-hello-neon-xmas--i-and-a', 'HotchPotch Hello Neon - xmas / I&A', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-itsnotpunusual-regular', 'HotchPotch ItsNotPunusual - regular', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-jam-sandwich-xmas--i-and-a', 'HotchPotch Jam Sandwich - xmas / I&A', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-lemonade-regular', 'HotchPotch Lemonade - regular', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-leopard-love-regular', 'HotchPotch Leopard Love - regular', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-lulu-xmas--i-and-a', 'HotchPotch LuLu - xmas / I&A', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-luxe-regular', 'HotchPotch Luxe - regular', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-marmalade-regular', 'HotchPotch Marmalade - regular', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-oh-dotty-regular', 'HotchPotch Oh Dotty - regular', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-oh-what-pun-xmas--i-and-a', 'HotchPotch Oh what pun! - xmas / I&A', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-orion-regular', 'HotchPotch Orion - regular', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-pixie-regular', 'HotchPotch Pixie - regular', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-playground-regular', 'HotchPotch Playground - regular', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-raspberry-regular', 'HotchPotch Raspberry - regular', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-rose-regular', 'HotchPotch Rose - regular', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-so-macho-regular', 'HotchPotch So Macho - regular', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-sticky-toffee-regular', 'HotchPotch Sticky Toffee - regular', 'Carte Blanche'
UNION ALL SELECT 'range-hotchpotch-vacation-regular', 'HotchPotch Vacation - regular', 'Carte Blanche'
UNION ALL SELECT 'range-catchy-images-regular', 'Catchy Images - regular', 'Catchy Images'
UNION ALL SELECT 'range-funny-side-up', 'Funny Side Up', 'Celebration Nation'
UNION ALL SELECT 'range-uddle', 'Uddle', 'Celebration Nation'
UNION ALL SELECT 'range-charly-clements', 'Charly Clements', 'Charly Clements'
UNION ALL SELECT 'range-cheeky-chops-marketplace', 'Cheeky Chops Marketplace', 'Cheeky Chops'
UNION ALL SELECT 'range-citrus-bunn', 'Citrus Bunn', 'Citrus Bunn Limited'
UNION ALL SELECT 'range-corrin-strain', 'Corrin Strain', 'Corrin Strain'
UNION ALL SELECT 'range-dalia-clark-design', 'Dalia Clark Design', 'Dalia Clark Design'
UNION ALL SELECT 'range-days-of-bloom-regular', 'Days of bloom - regular', 'Days of bloom'
UNION ALL SELECT 'range-days-of-bloom-xmas--i-and-a', 'Days of bloom - xmas / I&A', 'Days of bloom'
UNION ALL SELECT 'range-dean-morris', 'Dean Morris', 'Dean Morris'
UNION ALL SELECT 'range-deckled-edge', 'Deckled edge', 'Deckled Edge'
UNION ALL SELECT 'range-dinky-rouge', 'Dinky Rouge', 'Dinky Rouge'
UNION ALL SELECT 'range-doodles-by-ini', 'Doodles by Ini', 'Doodles by Ini'
UNION ALL SELECT 'range-dotty-black', 'Dotty Black', 'Dotty Black'
UNION ALL SELECT 'range-woezel-en-pip-regular', 'Woezel en Pip - regular', 'Dromenjager'
UNION ALL SELECT 'range-woezel-en-pip-xmas--i-and-a', 'Woezel en Pip - xmas / I&A', 'Dromenjager'
UNION ALL SELECT 'range-emma-proctor-designs', 'Emma Proctor Designs', 'Emma Proctor Designs'
UNION ALL SELECT 'range-endless-mae-regular', 'Endless Mae - regular', 'Endless Mae'
UNION ALL SELECT 'range-endless-mae-xmas--i-and-a', 'Endless Mae - xmas / I&A', 'Endless Mae'
UNION ALL SELECT 'range-fabienne-chapot-regular', 'Fabienne Chapot - regular', 'Fabienne Chapot'
UNION ALL SELECT 'range-fabienne-chapot-xmas--i-and-a', 'Fabienne Chapot - xmas / I&A', 'Fabienne Chapot'
UNION ALL SELECT 'range-fabriekshuys-regular', 'Fabriekshuys - regular', 'Fabriekshuys'
UNION ALL SELECT 'range-anonsense', 'Anonsense', 'Felt Studios Ltd.'
UNION ALL SELECT 'range-boom', 'Boom', 'Felt Studios Ltd.'
UNION ALL SELECT 'range-the-corrigan-sisters', 'The Corrigan Sisters', 'Felt Studios Ltd.'
UNION ALL SELECT 'range-fiep-westendorp-regular', 'Fiep Westendorp - regular', 'Fiep Westendorp'
UNION ALL SELECT 'range-fiep-westendorp-xmas--i-and-a', 'Fiep Westendorp - xmas / I&A', 'Fiep Westendorp'
UNION ALL SELECT 'range-pim-en-pom-regular', 'Pim en Pom - regular', 'Fiep Westendorp'
UNION ALL SELECT 'range-pim-en-pom-xmas--i-and-a', 'Pim en Pom - xmas / I&A', 'Fiep Westendorp'
UNION ALL SELECT 'range-filthy-sentiments', 'Filthy Sentiments', 'Filthy Sentiments'
UNION ALL SELECT 'range-frits-regular', 'Frits - regular', 'Frits'
UNION ALL SELECT 'range-frits-xmas--i-and-a', 'Frits - xmas / I&A', 'Frits'
UNION ALL SELECT 'range-funny-side-up-evd', 'Funny Side Up - EVD', 'Funny Side Up'
UNION ALL SELECT 'range-funny-side-up-ia--', 'Funny Side Up - IA  ', 'Funny Side Up'
UNION ALL SELECT 'range-go-la-la', 'Go La La', 'Go La La'
UNION ALL SELECT 'range-greetz-regular', 'Greetz - regular', 'Greetz'
UNION ALL SELECT 'range-greetz-xmas--i-and-a', 'Greetz - xmas / I&A', 'Greetz'
UNION ALL SELECT 'range-greetz-freestyle-regular', 'Greetz Freestyle - regular', 'Greetz'
UNION ALL SELECT 'range-mp6000-regular', 'MP6000 - regular', 'Greetz'
UNION ALL SELECT 'range-a-doodle-a-day-regular', 'A Doodle A Day - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-all-in-one-regular', 'All in one - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-animalparty-regular', 'AnimalParty - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-aquarell-color-regular', 'Aquarell color - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-babydreams-regular', 'BabyDreams - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-bbq-salsa-regular', 'BBQ Salsa - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-blossom-and-bloom-regular', 'Blossom&Bloom - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-bohoholidays-regular', 'BohoHolidays - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-bold-and-beyond-regular', 'Bold and Beyond - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-bubbly-fun-regular', 'Bubbly Fun - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-bundle-of-joy-regular', 'Bundle of Joy - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-cats-don_t-lie-regular', 'Cats don''t lie - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-cb-aileen-regular', 'CB - Aileen - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-cb-angela-regular', 'CB - Angela - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-cb-bianca-regular', 'CB - Bianca - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-cb-britt-regular', 'CB - Britt - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-cb-demi-regular', 'CB - Demi - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-cb-fieke-regular', 'CB - Fieke - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-cb-janita-regular', 'CB - Janita - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-cb-julia-regular', 'CB - Julia - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-cb-lizzy-regular', 'CB - Lizzy - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-cb-lotte-regular', 'CB - Lotte - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-cb-marissa-regular', 'CB - Marissa - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-cb-nicolette-regular', 'CB - Nicolette - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-cb-philippine-regular', 'CB - Philippine - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-cb-zoe-regular', 'CB - Zoe - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-cheers-to-you-regular', 'Cheers to you - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-cherry-on-top-regular', 'Cherry on top - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-colorfulmadness-regular', 'Colorfulmadness - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-colorfulsportsman-regular', 'ColorfulSportsman - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-cut-it-out-regular', 'Cut it out - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-dami-draws-regular', 'Dami Draws - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-dance-it-out-regular', 'Dance it out - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-desert-wind-regular', 'Desert Wind - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-dogs-don_t-lie-regular', 'Dogs don''t lie - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-dream-with-me-regular', 'Dream with me - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-dreams-come-true-regular', 'Dreams come true - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-duotone-fun-regular', 'Duotone Fun - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-embrace-the-magic-regular', 'Embrace the Magic - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-falalala-regular', 'Falalala - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-fiesta-regular', 'Fiesta - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-flip-side-regular', 'Flip side - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-floral-holiday-regular', 'Floral Holiday - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-focus-on-blue-regular', 'Focus on blue - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-fresh-start-regular', 'Fresh Start - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-funky-vibes-regular', 'Funky Vibes - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-go-with-the-flow-regular', 'Go with the flow - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-gold-christmas-regular', 'Gold Christmas - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-groovy-greetings-regular', 'Groovy Greetings - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-happy-always-regular', 'Happy always - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-happy-dicks-regular', 'Happy Dicks - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-happy-letters-regular', 'Happy Letters - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-happy-moments-regular', 'Happy Moments - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-happy-tits-regular', 'Happy Tits - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-hello-betty-regular', 'Hello Betty - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-hello-gorgeous-regular', 'Hello Gorgeous - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-hellodecember-regular', 'HelloDecember - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-holiday-after-hours-regular', 'Holiday After Hours - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-holidayblues--regular', 'HolidayBlues -regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-hollandse-meesters-regular', 'Hollandse Meesters - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-i-like-your-smiley-regular', 'I Like Your Smiley - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-i-saw-the-sign-regular', 'I Saw The Sign - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-i-see-patterns-regular', 'I See Patterns - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-it_s-a-wrap-regular', 'It''s a wrap - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-it_s-a-zoo-out-there-regular', 'It''s a zoo out there - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-jolly-happy-joy-regular', 'Jolly Happy Joy - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-jollyandbright-regular', 'JollyandBright - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-joy-to-the-world-regular', 'Joy to the world - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-kleinblue-regular', 'KleinBlue - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-later-alligator-regular', 'Later Alligator - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-legs-talk-about-it-regular', 'Legs talk about it - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-let_s-go-crazy-regular', 'Let’s go crazy - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-lieve-herfst-regular', 'Lieve Herfst - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-lifeline-regular', 'Lifeline - Regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-love-brush-regular', 'Love Brush - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-love-is-all-you-need-regular', 'Love is all you need - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-love-letters-regular', 'Love Letters - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-love-notes-regular', 'Love Notes - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-love-wins-regular', 'Love wins - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-lucky-star-regular', 'Lucky star - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-magic-monday-regular', 'Magic Monday - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-marble-christmas-regular', 'Marble Christmas - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-mark-my-words-regular', 'Mark my words - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-meet-harry-regular', 'Meet Harry - Regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-merry-and-cherry-regular', 'Merry And Cherry - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-merry-everything-regular', 'Merry everything - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-merrymore-regular', 'Merrymore - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-modernsparkle-regular', 'ModernSparkle - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-natural-shapes-regular', 'Natural Shapes - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-naughty-or-nice-regular', 'Naughty or nice - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-oh-baby-regular', 'Oh baby - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-oh-happy-days-regular', 'Oh Happy days - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-only-kind-words-regular', 'Only kind words - Regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-ooh-lala--regular', 'Ooh-Lala- regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-our-stories-regular', 'Our Stories - Regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-paper-trails-regular', 'Paper Trails - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-pastel-dreams-regular', 'Pastel Dreams - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-pawsome-cats-regular', 'Pawsome Cats - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-picture-perfect-regular', 'Picture Perfect - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-pixel-perfect-regular', 'Pixel Perfect - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-poppyfields-regular', 'PoppyFields - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-portraits-regular', 'Portraits - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-positivitea-regular', 'Positivitea - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-rain--and--sunshine-regular', 'Rain & Sunshine - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-rainbowsandstars-regular', 'RainbowsAndStars - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-revelation-halftone-regular', 'Revelation Halftone - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-say-cheese-regular', 'Say Cheese - Regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-say-it-out-loud-regular', 'Say It Out Loud - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-self-love-club-regular', 'Self Love Club - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-shine-bright-regular', 'Shine bright - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-showtime-regular', 'Showtime - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-size-matters--regular', 'Size matters  - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-snowflake-regular', 'Snowflake - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-speak-out-regular', 'Speak Out - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-springfling-regular', 'SpringFling - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-stardust-regular', 'Stardust - Regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-stay-wild-regular', 'Stay Wild - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-storylines-regular', 'Storylines - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-summer-nights-regular', 'Summer Nights - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-summer-romance-regular', 'Summer Romance - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-sunny-side-up-regular', 'Sunny Side Up - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-sweet-and-salty-regular', 'Sweet and Salty - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-sweet-little-note-regular', 'Sweet Little Note - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-sweet-lollipop-regular', 'Sweet Lollipop - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-sweet-sunrise-regular', 'Sweet sunrise - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-sweetheart-hero-regular', 'Sweetheart Hero - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-takkenfeest-regular', 'Takkenfeest - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-tequila-regular', 'Tequila - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-that-doesn_t-bug-me-regular', 'That doesn''t bug me - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-the-good-gets-better-regular', 'The Good gets Better - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-the-power-of-flower-regular', 'The Power Of Flower - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-true-blue--regular', 'True blue  - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-twinklelittlestar-regular', 'TwinkleLittleStar - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-unconditional-fun-regular', 'Unconditional Fun - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-under-my-umbrella--regular', 'Under my Umbrella  - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-very-good-very-nice-regular', 'Very good very nice - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-voxelville-regular', 'Voxelville - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-vrolijke-vriendjes-regular', 'Vrolijke Vriendjes - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-whambam-regular', 'Whambam - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-wildfire-regular', 'WildFire - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-wonderful-wishes-regular', 'Wonderful wishes - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-you_ve-got-this-regular', 'You’ve Got This - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-your-typical-chaos-regular', 'Your Typical Chaos - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-you_re-my-type-regular', 'You''re my type - regular', 'Greetz - Designer Collections'
UNION ALL SELECT 'range-haori-regular', 'Haori - regular', 'Haori'
UNION ALL SELECT 'range-haori-xmas--i-and-a', 'Haori - xmas / I&A', 'Haori'
UNION ALL SELECT 'range-hello-munki', 'Hello Munki', 'Hello Munki'
UNION ALL SELECT 'range-say-it', 'Say It', 'Hello Munki'
UNION ALL SELECT 'range-ikpakjein-regular', 'IKPAKJEIN - regular', 'IKPAKJEIN'
UNION ALL SELECT 'range-mila-regular', 'MILA - Regular', 'IKPAKJEIN'
UNION ALL SELECT 'range-ingrid-berendsen-regular', 'Ingrid Berendsen - regular', 'Ingrid Berendsen'
UNION ALL SELECT 'range-ingrid-berendsen-xmas--i-and-a', 'Ingrid Berendsen - xmas / I&A', 'Ingrid Berendsen'
UNION ALL SELECT 'range-isabel-clarke-izzy-likes-to-doodle', 'Isabel Clarke - Izzy Likes to Doodle', 'Isabel Clarke (Izzy Likes to Doodle)'
UNION ALL SELECT 'range-jem-and-jack-regular', 'Jem&Jack - regular', 'Jem&Jack'
UNION ALL SELECT 'range-jem-and-jack-xmas--i-and-a', 'Jem&Jack - xmas / I&A', 'Jem&Jack'
UNION ALL SELECT 'range-jenny-seddon', 'Jenny Seddon', 'Jenny Seddon'
UNION ALL SELECT 'range-jerry-tapscott', 'Jerry Tapscott', 'Jerry Tapscott'
UNION ALL SELECT 'range-jess-rose-illustration', 'Jess Rose Illustration', 'Jess Rose'
UNION ALL SELECT 'range-creativeingrid', 'CreativeIngrid', 'Jewel Branding'
UNION ALL SELECT 'range-mia-whittemore', 'Mia Whittemore', 'Jewel Branding'
UNION ALL SELECT 'range-happy-jackson', 'Happy Jackson', 'JJL Rights'
UNION ALL SELECT 'range-jolly-awesome', 'Jolly Awesome', 'Jolly Awesome'
UNION ALL SELECT 'range-judith-stam-regular', 'Judith Stam - regular', 'Judith Stam'
UNION ALL SELECT 'range-judith-stam-xmas--i-and-a', 'Judith Stam - xmas / I&A', 'Judith Stam'
UNION ALL SELECT 'range-karmuka', 'Karmuka', 'Karmuka'
UNION ALL SELECT 'range-katie-abey-design', 'Katie Abey Design', 'Katie Abey Design'
UNION ALL SELECT 'range-broken-biscuits', 'Broken Biscuits', 'Katt Jones Hulafig'
UNION ALL SELECT 'range-hello-petal', 'Hello Petal', 'Katt Jones Hulafig'
UNION ALL SELECT 'range-katt-jones-hulafig', 'Katt Jones Hulafig', 'Katt Jones Hulafig'
UNION ALL SELECT 'range-dikkie-dik-regular', 'Dikkie Dik - regular', 'Kbizz'
UNION ALL SELECT 'range-dikkie-dik-xmas--i-and-a', 'Dikkie Dik - xmas / I&A', 'Kbizz'
UNION ALL SELECT 'range-noelle-smit-regular', 'Noëlle Smit - regular', 'Kbizz'
UNION ALL SELECT 'range-kitchen-of-smiles-regular', 'Kitchen of smiles - regular', 'Kitchen of smiles'
UNION ALL SELECT 'range-kitsch-noir', 'Kitsch Noir', 'Kitsch Noir'
UNION ALL SELECT 'range-frans-hals-regular', 'Frans Hals - regular', 'Klaas de Jong'
UNION ALL SELECT 'range-klaas-de-jong-regular', 'Klaas de Jong - regular', 'Klaas de Jong'
UNION ALL SELECT 'range-rijksmuseum-regular', 'Rijksmuseum - regular', 'Klaas de Jong'
UNION ALL SELECT 'range-van-gogh-regular', 'Van Gogh - regular', 'Klaas de Jong'
UNION ALL SELECT 'range-klara-hawkins', 'Klara Hawkins', 'Klara Hawkins'
UNION ALL SELECT 'range-kleine-twinkeltjes-regular', 'Kleine Twinkeltjes - regular', 'Kleine Twinkeltjes'
UNION ALL SELECT 'range-kleine-vlindervoetjes-regular', 'Kleine Vlindervoetjes - regular', 'Kleine Vlindervoetjes'
UNION ALL SELECT 'range-me-without-you', 'Me Without You', 'Last Lemon Productions Ltd'
UNION ALL SELECT 'range-letters-by-julia', 'Letters By Julia', 'Letters by Julia'
UNION ALL SELECT 'range-lief-leven-regular', 'Lief Leven - regular', 'Lief Leven'
UNION ALL SELECT 'range-lief-leven-xmas--i-and-a', 'Lief Leven - xmas / I&A', 'Lief Leven'
UNION ALL SELECT 'range-beautiful-planet', 'Beautiful Planet', 'Ling Design'
UNION ALL SELECT 'range-letterpress', 'Letterpress', 'Ling Design'
UNION ALL SELECT 'range-ling-design', 'Ling Design', 'Ling Design'
UNION ALL SELECT 'range-talking-pictures', 'Talking Pictures', 'Ling Design'
UNION ALL SELECT 'range-the-curious-inksmith', 'The Curious Inksmith', 'Ling Design'
UNION ALL SELECT 'range-the-wild-life', 'The wild life', 'Ling Design'
UNION ALL SELECT 'range-little-dutch-regular', 'Little Dutch - regular', 'Little Dutch'
UNION ALL SELECT 'range-little-dutch-xmas--i-and-a', 'Little Dutch - xmas / I&A', 'Little Dutch'
UNION ALL SELECT 'range-lizzarddesigns-regular', 'Lizzarddesigns - regular', 'Lizzarddesigns'
UNION ALL SELECT 'range-lizzarddesigns-xmas--i-and-a', 'Lizzarddesigns - xmas / I&A', 'Lizzarddesigns'
UNION ALL SELECT 'range-love-repeat-regular', 'Love Repeat - regular', 'Luckz'
UNION ALL SELECT 'range-luckz-regular', 'Luckz - regular', 'Luckz'
UNION ALL SELECT 'range-luckz-xmas--i-and-a', 'Luckz - xmas / I&A', 'Luckz'
UNION ALL SELECT 'range-lucy-maggie', 'Lucy Maggie', 'Lucy Maggie'
UNION ALL SELECT 'range-lucy-pearce-designs', 'Lucy Pearce designs', 'Lucy Pearce Designs'
UNION ALL SELECT 'range-maartje-bodt-regular', 'Maartje Bodt - regular', 'Maartje Bodt'
UNION ALL SELECT 'range-maartje-bodt-xmas--i-and-a', 'Maartje Bodt - xmas / I&A', 'Maartje Bodt'
UNION ALL SELECT 'range-make-a-wish-regular', 'Make a Wish - regular', 'Make a Wish'
UNION ALL SELECT 'range-marieke-witke-regular', 'Marieke Witke - regular', 'Marieke Witke'
UNION ALL SELECT 'range-marieke-witke-xmas--i-and-a', 'Marieke Witke - xmas / I&A', 'Marieke Witke'
UNION ALL SELECT 'range-melli-mello-regular', 'Melli Mello - regular', 'Melli Mello'
UNION ALL SELECT 'range-melli-mello-xmas--i-and-a', 'Melli Mello - xmas / I&A', 'Melli Mello'
UNION ALL SELECT 'range-melolelo-regular', 'Melolelo - regular', 'Melolelo'
UNION ALL SELECT 'range-memelou', 'Memelou', 'Memelou'
UNION ALL SELECT 'range-milestone-regular', 'Milestone - regular', 'Milestone - Sophia Vesting Holding'
UNION ALL SELECT 'range-millicent-venton', 'Millicent Venton', 'Millicent Venton'
UNION ALL SELECT 'range-moniek-peek-regular', 'Moniek Peek - regular', 'Moniek Peek'
UNION ALL SELECT 'range-moniek-peek-xmas--i-and-a', 'Moniek Peek - xmas / I&A', 'Moniek Peek'
UNION ALL SELECT 'range-characterful', 'Characterful', 'Moonpig'
UNION ALL SELECT 'range-kinship', 'Kinship', 'Moonpig'
UNION ALL SELECT 'range-sketchy-characters', 'Sketchy Characters', 'Moonpig'
UNION ALL SELECT 'range-mp-disney-regular', 'MP - Disney - Regular', 'MP - Disney'
UNION ALL SELECT 'range-mp-disney-xmasia', 'MP - Disney - xmas/IA', 'MP - Disney'
UNION ALL SELECT 'range-mp-disney-princesses-regular', 'MP - Disney Princesses - Regular', 'MP - Disney'
UNION ALL SELECT 'range-mp-disney-princesses-xmasia', 'MP - Disney Princesses - xmas/IA', 'MP - Disney'
UNION ALL SELECT 'range-mp-frozen-regular', 'MP - Frozen - Regular', 'MP - Disney'
UNION ALL SELECT 'range-mp-frozen-xmasia', 'MP - Frozen - xmas/IA', 'MP - Disney'
UNION ALL SELECT 'range-mp-mickey-mouse-regular', 'MP - Mickey Mouse - Regular', 'MP - Disney'
UNION ALL SELECT 'range-mp-mickey-mouse-xmasia', 'MP - Mickey Mouse - xmas/IA', 'MP - Disney'
UNION ALL SELECT 'range-mp-minnie-mouse-regular', 'MP - Minnie Mouse - Regular', 'MP - Disney'
UNION ALL SELECT 'range-mp-minnie-mouse-xmasia', 'MP - Minnie Mouse - xmas/IA', 'MP - Disney'
UNION ALL SELECT 'range-mp-moana-regular', 'MP - Moana - Regular', 'MP - Disney'
UNION ALL SELECT 'range-mp-moana-xmasia', 'MP - Moana - xmas/IA', 'MP - Disney'
UNION ALL SELECT 'range-mp-winnie-the-pooh-regular', 'MP - Winnie-the-pooh - Regular', 'MP - Disney'
UNION ALL SELECT 'range-mp-winnie-the-pooh-xmasia', 'MP - Winnie-the-pooh - xmas/IA', 'MP - Disney'
UNION ALL SELECT 'range-mp-marvel-regular', 'MP - Marvel - Regular', 'MP - Marvel'
UNION ALL SELECT 'range-mp-marvel-xmasia', 'MP - Marvel - xmas/IA', 'MP - Marvel'
UNION ALL SELECT 'range-mp-spiderman-regular', 'MP - Spiderman - Regular', 'MP - Marvel'
UNION ALL SELECT 'range-mp-spiderman-xmasia', 'MP - Spiderman - xmas/IA', 'MP - Marvel'
UNION ALL SELECT 'range-mp-the-avengers-regular', 'MP - The Avengers - Regular', 'MP - Marvel'
UNION ALL SELECT 'range-mp-the-avengers-xmasia', 'MP - The Avengers - xmas/IA', 'MP - Marvel'
UNION ALL SELECT 'range-mp-starwars-regular', 'MP - Starwars - Regular', 'MP - Starwars'
UNION ALL SELECT 'range-mp-starwars-xmasia', 'MP - Starwars - xmas/IA', 'MP - Starwars'
UNION ALL SELECT 'range-mp-despicable-me-regular', 'MP - Despicable me - Regular', 'MP - Universal'
UNION ALL SELECT 'range-mp-despicable-me-xmasia', 'MP - Despicable me - xmas/IA', 'MP - Universal'
UNION ALL SELECT 'range-mp-universal-regular', 'MP - Universal - Regular', 'MP - Universal'
UNION ALL SELECT 'range-mp-universal-xmasia', 'MP - Universal - xmas/IA', 'MP - Universal'
UNION ALL SELECT 'range-natalie-alex-designs', 'Natalie Alex Designs', 'Natalie Alex Designs'
UNION ALL SELECT 'range-neil-clark-design', 'Neil CLark Design', 'Neil Clark'
UNION ALL SELECT 'range-doodles-regular', 'Doodles - regular', 'Nicholson'
UNION ALL SELECT 'range-doodles-xmas--i-and-a', 'Doodles - xmas / I&A', 'Nicholson'
UNION ALL SELECT 'range-old-dutch-regular', 'Old Dutch - regular', 'Nicholson'
UNION ALL SELECT 'range-old-dutch-xmas--i-and-a', 'Old Dutch - xmas / I&A', 'Nicholson'
UNION ALL SELECT 'range-nijntje-regular', 'Nijntje - regular', 'Nijntje'
UNION ALL SELECT 'range-nijntje-xmas--i-and-a', 'Nijntje - xmas / I&A', 'Nijntje'
UNION ALL SELECT 'range-okey-dokey-design', 'Okey Dokey Design', 'Okey Dokey Design'
UNION ALL SELECT 'range-jan-van-haasteren-regular', 'Jan van Haasteren - regular', 'Orange Licensing BV'
UNION ALL SELECT 'range-jan-van-haasteren-xmas--i-and-a', 'Jan van Haasteren - xmas / I&A', 'Orange Licensing BV'
UNION ALL SELECT 'range-jan-van-haasteren-junior-regular', 'Jan van Haasteren Junior - Regular', 'Orange Licensing BV'
UNION ALL SELECT 'range-jan-van-haasteren-junior-xmas--i-and-a', 'Jan van Haasteren Junior - xmas / I&A', 'Orange Licensing BV'
UNION ALL SELECT 'range-janneke-brinkman-regular', 'Janneke Brinkman - regular', 'Orange Licensing BV'
UNION ALL SELECT 'range-janneke-brinkman-xmas--i-and-a', 'Janneke Brinkman - xmas / I&A', 'Orange Licensing BV'
UNION ALL SELECT 'range-michelle-dujardin-regular', 'Michelle Dujardin - regular', 'Orange Licensing BV'
UNION ALL SELECT 'range-michelle-dujardin-xmas--i-and-a', 'Michelle Dujardin - xmas / I&A', 'Orange Licensing BV'
UNION ALL SELECT 'range-papagrazi', 'Papagrazi', 'Papagrazi Limited'
UNION ALL SELECT 'range-1974-regular', '1974 - regular', 'Paperclip'
UNION ALL SELECT 'range-colibri-xmas--i-and-a', 'Colibri - xmas / I&A', 'Paperclip'
UNION ALL SELECT 'range-focus-regular', 'Focus - regular', 'Paperclip'
UNION ALL SELECT 'range-gilan-regular', 'Gilan - regular', 'Paperclip'
UNION ALL SELECT 'range-heart--and--soul-regular', 'Heart & soul - regular', 'Paperclip'
UNION ALL SELECT 'range-highline-xmas--i-and-a', 'Highline - xmas / I&A', 'Paperclip'
UNION ALL SELECT 'range-indie-regular', 'Indie - regular', 'Paperclip'
UNION ALL SELECT 'range-le-chic-xmas--i-and-a', 'Le Chic - xmas / I&A', 'Paperclip'
UNION ALL SELECT 'range-levels-regular', 'Levels - regular', 'Paperclip'
UNION ALL SELECT 'range-lifetimes-xmas--i-and-a', 'Lifetimes - xmas / I&A', 'Paperclip'
UNION ALL SELECT 'range-mingface-regular', 'Mingface - regular', 'Paperclip'
UNION ALL SELECT 'range-nolita-regular', 'Nolita - regular', 'Paperclip'
UNION ALL SELECT 'range-nolita-xmas--i-and-a', 'Nolita - xmas / I&A', 'Paperclip'
UNION ALL SELECT 'range-omg-regular', 'OMG - regular', 'Paperclip'
UNION ALL SELECT 'range-omg-xmas--i-and-a', 'OMG - xmas / I&A', 'Paperclip'
UNION ALL SELECT 'range-on-the-dot-regular', 'On the Dot - regular', 'Paperclip'
UNION ALL SELECT 'range-paperclip-regular', 'Paperclip - regular', 'Paperclip'
UNION ALL SELECT 'range-paperclip-xmas--i-and-a', 'Paperclip - xmas / I&A', 'Paperclip'
UNION ALL SELECT 'range-papercraft-regular', 'Papercraft - regular', 'Paperclip'
UNION ALL SELECT 'range-partybus-regular', 'Partybus - regular', 'Paperclip'
UNION ALL SELECT 'range-petit-doodle-regular', 'Petit Doodle - regular', 'Paperclip'
UNION ALL SELECT 'range-petit-doodle-xmas--i-and-a', 'Petit Doodle - xmas / I&A', 'Paperclip'
UNION ALL SELECT 'range-photofactory-regular', 'Photofactory - regular', 'Paperclip'
UNION ALL SELECT 'range-popcard-regular', 'PopCard - regular', 'Paperclip'
UNION ALL SELECT 'range-sooo-happy-regular', 'Sooo Happy - regular', 'Paperclip'
UNION ALL SELECT 'range-sports-regular', 'Sports - regular', 'Paperclip'
UNION ALL SELECT 'range-the-zoo-regular', 'The Zoo - regular', 'Paperclip'
UNION ALL SELECT 'range-together-regular', 'Together - regular', 'Paperclip'
UNION ALL SELECT 'range-tralala-regular', 'Tralala - regular', 'Paperclip'
UNION ALL SELECT 'range-vintage-vibes-regular', 'Vintage Vibes - regular', 'Paperclip'
UNION ALL SELECT 'range-papercute-regular', 'Papercute - regular', 'Papercute'
UNION ALL SELECT 'range-papercute-xmas--i-and-a', 'Papercute - xmas / I&A', 'Papercute'
UNION ALL SELECT 'range-amaretto', 'Amaretto', 'Paperlink'
UNION ALL SELECT 'range-axel', 'Axel', 'Paperlink'
UNION ALL SELECT 'range-bangers-and-flash', 'Bangers and Flash', 'Paperlink'
UNION ALL SELECT 'range-choose-joy', 'Choose Joy', 'Paperlink'
UNION ALL SELECT 'range-fruitloops', 'Fruitloops', 'Paperlink'
UNION ALL SELECT 'range-la-la-land', 'La La Land', 'Paperlink'
UNION ALL SELECT 'range-lemon-sorbet-christmas', 'Lemon Sorbet Christmas', 'Paperlink'
UNION ALL SELECT 'range-onyx', 'Onyx', 'Paperlink'
UNION ALL SELECT 'range-paperlink', 'Paperlink', 'Paperlink'
UNION ALL SELECT 'range-papilion', 'Papilion', 'Paperlink'
UNION ALL SELECT 'range-pina-colada', 'Pina Colada', 'Paperlink'
UNION ALL SELECT 'range-skylark', 'Skylark', 'Paperlink'
UNION ALL SELECT 'range-pearl-and-ivy', 'Pearl and Ivy', 'Pearl Ivy'
UNION ALL SELECT 'range-petit-konijn-regular', 'Petit Konijn - regular', 'Petit Konijn'
UNION ALL SELECT 'range-photoflash-regular', 'Photoflash - regular', 'Photoflash'
UNION ALL SELECT 'range-etched', 'Etched', 'Pigment'
UNION ALL SELECT 'range-funny-works', 'Funny Works', 'Pigment'
UNION ALL SELECT 'range-hey-girl', 'Hey Girl', 'Pigment'
UNION ALL SELECT 'range-pigment', 'Pigment', 'Pigment'
UNION ALL SELECT 'range-pigment-30k', 'Pigment 30K', 'Pigment'
UNION ALL SELECT 'range-pigment-emporium', 'Pigment Emporium', 'Pigment'
UNION ALL SELECT 'range-pigment-everyday', 'Pigment Everyday', 'Pigment'
UNION ALL SELECT 'range-pigment-hello-there', 'Pigment Hello There', 'Pigment'
UNION ALL SELECT 'range-pinot-grigio', 'Pinot Grigio', 'Pigment'
UNION ALL SELECT 'range-porcelain', 'Porcelain', 'Pigment'
UNION ALL SELECT 'range-the-happy-news', 'The Happy News', 'Pigment Productions Ltd.'
UNION ALL SELECT 'range-the-happy-news-mother_s-day', 'The Happy News Mother''s Day', 'Pigment Productions Ltd.'
UNION ALL SELECT 'range-pink-stories-regular', 'Pink Stories - regular', 'Pink Stories'
UNION ALL SELECT 'range-pink-stories-xmas--i-and-a', 'Pink Stories - xmas / I&A', 'Pink Stories'
UNION ALL SELECT 'range-playful-indian', 'Playful Indian', 'Playful Indian'
UNION ALL SELECT 'range-poet-and-painter', 'Poet and painter', 'Poet and painter'
UNION ALL SELECT 'range-quitting-hollywood', 'Quitting Hollywood', 'Quitting Hollywood'
UNION ALL SELECT 'range-redback-cards-limited', 'Redback Cards Limited', 'Redback Cards Limited'
UNION ALL SELECT 'range-rich-t', 'Rich T', 'Rich T'
UNION ALL SELECT 'range-rumble-cards', 'Rumble Cards', 'Rumble Cards'
UNION ALL SELECT 'range-sadler-jones', 'Sadler Jones', 'SADLER JONES LTD'
UNION ALL SELECT 'range-sandysign-regular', 'Sandysign - regular', 'Sandysign'
UNION ALL SELECT 'range-sandysign-xmas--i-and-a', 'Sandysign - xmas / I&A', 'Sandysign'
UNION ALL SELECT 'range-saskia-rasink-regular', 'Saskia Rasink - regular', 'Saskia Rasink'
UNION ALL SELECT 'range-saskia-rasink-xmas--i-and-a', 'Saskia Rasink - xmas / I&A', 'Saskia Rasink'
UNION ALL SELECT 'range-sooshichacha', 'Sooshichacha', 'Sooshichacha'
UNION ALL SELECT 'range-ideal-type', 'Ideal Type', 'Stella Isaac Illustration'
UNION ALL SELECT 'range-stella-isaac-illustration', 'Stella Isaac Illustration', 'Stella Isaac Illustration'
UNION ALL SELECT 'range-stichting-vrienden-van-loesje-regular', 'Stichting Vrienden van Loesje - regular', 'Stichting Vrienden van Loesje'
UNION ALL SELECT 'range-stichting-vrienden-van-loesje-xmas--i-and-a', 'Stichting Vrienden van Loesje - xmas / I&A', 'Stichting Vrienden van Loesje'
UNION ALL SELECT 'range-studio-pets-regular', 'Studio Pets - regular', 'Studio Pets'
UNION ALL SELECT 'range-studio-pets-xmas--i-and-a', 'Studio Pets - xmas / I&A', 'Studio Pets'
UNION ALL SELECT 'range-studio-sundae', 'Studio Sundae', 'Studio Sundae (Holly Sims)'
UNION ALL SELECT 'range-tante-kaartje-regular', 'Tante Kaartje - regular', 'Tante Kaartje'
UNION ALL SELECT 'range-tante-kaartje-xmas--i-and-a', 'Tante Kaartje - xmas / I&A', 'Tante Kaartje'
UNION ALL SELECT 'range-cardy-club', 'Cardy Club', 'The Cardy Club'
UNION ALL SELECT 'range-the-london-studio', 'The London Studio', 'The London Studio'
UNION ALL SELECT 'range-hola-happy', 'Hola Happy', 'The Studio of Mr & Mrs Downing'
UNION ALL SELECT 'range-little-acorns', 'Little Acorns', 'The Studio of Mr & Mrs Downing'
UNION ALL SELECT 'range-menagerie-a-deux', 'Menagerie A Deux', 'The Studio of Mr & Mrs Downing'
UNION ALL SELECT 'range-moonbeams', 'Moonbeams', 'The Studio of Mr & Mrs Downing'
UNION ALL SELECT 'range-a-peculiar-publication', 'A Peculiar Publication', 'TheDogsDoodahs'
UNION ALL SELECT 'range-jam-and-toast', 'Jam and Toast', 'TheDogsDoodahs'
UNION ALL SELECT 'range-wet-you-wistles', 'Wet you Wistles', 'TheDogsDoodahs'
UNION ALL SELECT 'range-a-peculiar-publication', 'A Peculiar Publication', 'TheDogsDoodahs.com'
UNION ALL SELECT 'range-jam-and-toast', 'Jam and Toast', 'TheDogsDoodahs.com'
UNION ALL SELECT 'range-wet-you-wistles', 'Wet you Wistles', 'TheDogsDoodahs.com'
UNION ALL SELECT 'range-artbox-regular', 'Artbox - regular', 'TMS'
UNION ALL SELECT 'range-bloom-regular', 'Bloom - regular', 'TMS'
UNION ALL SELECT 'range-blueberrypie-regular', 'BlueberryPie - regular', 'TMS'
UNION ALL SELECT 'range-boutique-chic-regular', 'Boutique Chic - regular', 'TMS'
UNION ALL SELECT 'range-butterscotch-regular', 'Butterscotch - regular', 'TMS'
UNION ALL SELECT 'range-campus-regular', 'Campus - regular', 'TMS'
UNION ALL SELECT 'range-confetti-regular', 'Confetti - regular', 'TMS'
UNION ALL SELECT 'range-copacabana-regular', 'Copacabana - regular', 'TMS'
UNION ALL SELECT 'range-counting-stars-regular', 'Counting Stars - regular', 'TMS'
UNION ALL SELECT 'range-cuddles-regular', 'Cuddles - regular', 'TMS'
UNION ALL SELECT 'range-everyday-close-up-regular', 'Everyday Close Up - regular', 'TMS'
UNION ALL SELECT 'range-glow-regular', 'Glow - regular', 'TMS'
UNION ALL SELECT 'range-gold-fever-regular', 'Gold Fever - regular', 'TMS'
UNION ALL SELECT 'range-goldelicious-regular', 'Goldelicious - regular', 'TMS'
UNION ALL SELECT 'range-halcyon-regular', 'Halcyon - regular', 'TMS'
UNION ALL SELECT 'range-happiness-handmade-regular', 'Happiness Handmade - regular', 'TMS'
UNION ALL SELECT 'range-little-people-regular', 'Little People - regular', 'TMS'
UNION ALL SELECT 'range-love-it-regular', 'Love It - regular', 'TMS'
UNION ALL SELECT 'range-luna-regular', 'Luna - regular', 'TMS'
UNION ALL SELECT 'range-monster-collectie-regular', 'Monster Collectie - regular', 'TMS'
UNION ALL SELECT 'range-mylo-regular', 'Mylo - regular', 'TMS'
UNION ALL SELECT 'range-party-animals-regular', 'Party Animals - regular', 'TMS'
UNION ALL SELECT 'range-petit-pois-regular', 'Petit Pois - regular', 'TMS'
UNION ALL SELECT 'range-rio-brights-regular', 'Rio Brights - regular', 'TMS'
UNION ALL SELECT 'range-scribbles-regular', 'Scribbles - regular', 'TMS'
UNION ALL SELECT 'range-splash-colour-regular', 'Splash Colour - regular', 'TMS'
UNION ALL SELECT 'range-tequila-sunrise-regular', 'Tequila Sunrise - regular', 'TMS'
UNION ALL SELECT 'range-tms-regular', 'TMS - regular', 'TMS'
UNION ALL SELECT 'range-tms-xmas--i-and-a', 'TMS - xmas / I&A', 'TMS'
UNION ALL SELECT 'range-twinny-regular', 'Twinny - regular', 'TMS'
UNION ALL SELECT 'range-cute-as-a-button-regular', 'Cute as a button - regular', 'Tsjip'
UNION ALL SELECT 'range-cute-as-a-button-xmas--i-and-a', 'Cute as a button - xmas / I&A', 'Tsjip'
UNION ALL SELECT 'range-hippieness-regular', 'Hippieness - regular', 'Tsjip'
UNION ALL SELECT 'range-tsjip-regular', 'Tsjip - regular', 'Tsjip'
UNION ALL SELECT 'range-tsjip-xmas--i-and-a', 'Tsjip - xmas / I&A', 'Tsjip'
UNION ALL SELECT 'range-black-floral-regular', 'Black Floral - regular', 'UK Greetings'
UNION ALL SELECT 'range-boho-bloom-regular', 'Boho Bloom - regular', 'UK Greetings'
UNION ALL SELECT 'range-esprit-regular', 'Esprit - regular', 'UK Greetings'
UNION ALL SELECT 'range-flower-bomb-regular', 'Flower Bomb - regular', 'UK Greetings'
UNION ALL SELECT 'range-uk-greetings-regular', 'UK Greetings - regular', 'UK Greetings'
UNION ALL SELECT 'range-uk-greetings-xmas--i-and-a', 'UK Greetings - xmas / I&A', 'UK Greetings'
UNION ALL SELECT 'range-ukg', 'UKG', 'UKG ( UK Greetings)'
UNION ALL SELECT 'range-vreemde-vogels-regular', 'Vreemde vogels - regular', 'Vreemde vogels'
UNION ALL SELECT 'range-vreemde-vogels-xmas--i-and-a', 'Vreemde vogels - xmas / I&A', 'Vreemde vogels'
UNION ALL SELECT 'range-yh-tekent-regular', 'YH Tekent - regular', 'YH Tekent'
UNION ALL SELECT 'range-zusss-regular', 'Zusss - regular', 'Zusss'
UNION ALL SELECT 'range-zusss-xmas--i-and-a', 'Zusss - xmas / I&A', 'Zusss'
UNION ALL SELECT 'range-lizzy-pikaar-regular', 'Lizzy Pikaar - regular', 'Lizzy Pikaar'
UNION ALL SELECT 'range-lizzy-pikaar-xmas--i-and-a', 'Lizzy Pikaar - xmas / I&A', 'Lizzy Pikaar'
UNION ALL SELECT 'range-tangled', 'Tangled', 'Unspecified'
