CREATE OR REPLACE VIEW export_occasions_view 
AS
SELECT 'anniversary' AS 'entity_key', 'Anniversary' AS 'name'
UNION ALL SELECT 'anniversary-work-anniversary', 'Anniversary - Work anniversary'
UNION ALL SELECT 'anniversary-work-anniversary-anniversary-1-year-working-from-home', 'Anniversary - Work anniversary - Anniversary 1 year working from home'
UNION ALL SELECT 'aoc-think', 'AOC think'
UNION ALL SELECT 'baby-party-invitations', 'Baby party (invitations)'
UNION ALL SELECT 'baby-shower-invitations', 'Baby shower (invitations)'
UNION ALL SELECT 'bachelor-party-invitations', 'Bachelor party (invitations)'
UNION ALL SELECT 'back-to-school-cards', 'Back to school cards'
UNION ALL SELECT 'back-to-school-cards-highschool', 'Back to school cards - Highschool'
UNION ALL SELECT 'back-to-school-cards-new-schoolyear', 'Back to school cards - New schoolyear'
UNION ALL SELECT 'back-to-school-cards-new-schoolyear-highschool', 'Back to school cards - New schoolyear - Highschool'
UNION ALL SELECT 'baptism-and-communion-invitations', 'Baptism and communion (invitations)'
UNION ALL SELECT 'birth', 'Birth'
UNION ALL SELECT 'birth-birth-premature', 'Birth - Birth premature'
UNION ALL SELECT 'birth-birth-rainbow-child', 'Birth - Birth rainbow child'
UNION ALL SELECT 'birth-birth-with-handicap', 'Birth - Birth with handicap'
UNION ALL SELECT 'birth-cards-birth', 'Birth cards (Birth)'
UNION ALL SELECT 'birth-cards-birth-birth-cards-boy', 'Birth cards (Birth) - Birth cards (boy)'
UNION ALL SELECT 'birthday', 'Birthday'
UNION ALL SELECT 'birthday-birthday-belated-wishes', 'Birthday - Birthday belated Wishes'
UNION ALL SELECT 'birthday-birthday-from-distance', 'Birthday - Birthday from distance'
UNION ALL SELECT 'birthday-birthday-in-dialect', 'Birthday - Birthday in dialect'
UNION ALL SELECT 'birthday-birthday-leap-year', 'Birthday - Birthday leap year'
UNION ALL SELECT 'birthday-birthday-with-age', 'Birthday - Birthday with age'
UNION ALL SELECT 'birthday-birthday-with-star-sign', 'Birthday - Birthday with star sign'
UNION ALL SELECT 'birthday-invitation-invitations', 'Birthday invitation (invitations)'
UNION ALL SELECT 'birthday-invitation-invitations-16-years', 'Birthday invitation (invitations) - 16 years'
UNION ALL SELECT 'birthday-invitation-invitations-18-years', 'Birthday invitation (invitations) - 18 years'
UNION ALL SELECT 'birthday-invitation-invitations-21-years', 'Birthday invitation (invitations) - 21 years'
UNION ALL SELECT 'birthday-invitation-invitations-25-years', 'Birthday invitation (invitations) - 25 years'
UNION ALL SELECT 'birthday-invitation-invitations-30-years', 'Birthday invitation (invitations) - 30 years'
UNION ALL SELECT 'birthday-invitation-invitations-40-years', 'Birthday invitation (invitations) - 40 years'
UNION ALL SELECT 'birthday-invitation-invitations-50-years', 'Birthday invitation (invitations) - 50 years'
UNION ALL SELECT 'birthday-invitation-invitations-60-years', 'Birthday invitation (invitations) - 60 years'
UNION ALL SELECT 'birthday-invitation-invitations-70-years', 'Birthday invitation (invitations) - 70 years'
UNION ALL SELECT 'birthday-invitation-invitations-age-invitations', 'Birthday invitation (invitations) - Age invitations'
UNION ALL SELECT 'birthday-invitation-invitations-age-invitations-21-years', 'Birthday invitation (invitations) - Age invitations - 21 years'
UNION ALL SELECT 'birthday-invitation-invitations-age-invitations-25-years', 'Birthday invitation (invitations) - Age invitations - 25 years'
UNION ALL SELECT 'birthday-invitation-invitations-age-invitations-30-years', 'Birthday invitation (invitations) - Age invitations - 30 years'
UNION ALL SELECT 'birthday-invitation-invitations-age-invitations-40-years', 'Birthday invitation (invitations) - Age invitations - 40 years'
UNION ALL SELECT 'birthday-invitation-invitations-age-invitations-50-years', 'Birthday invitation (invitations) - Age invitations - 50 years'
UNION ALL SELECT 'birthday-invitation-invitations-age-invitations-60-years', 'Birthday invitation (invitations) - Age invitations - 60 years'
UNION ALL SELECT 'birthday-invitation-invitations-age-invitations-70-years', 'Birthday invitation (invitations) - Age invitations - 70 years'
UNION ALL SELECT 'birthday-invitation-invitations-age-invitations-80-years', 'Birthday invitation (invitations) - Age invitations - 80 years'
UNION ALL SELECT 'birthday-invitation-invitations-changeable-age', 'Birthday invitation (invitations) - Changeable age'
UNION ALL SELECT 'birthday-invitation-invitations-changeable-age-16-years', 'Birthday invitation (invitations) - Changeable age - 16 years'
UNION ALL SELECT 'birthday-invitation-invitations-changeable-age-21-years', 'Birthday invitation (invitations) - Changeable age - 21 years'
UNION ALL SELECT 'birthday-invitation-invitations-changeable-age-25-years', 'Birthday invitation (invitations) - Changeable age - 25 years'
UNION ALL SELECT 'birthday-invitation-invitations-changeable-age-30-years', 'Birthday invitation (invitations) - Changeable age - 30 years'
UNION ALL SELECT 'birthday-invitation-invitations-changeable-age-age-invitations', 'Birthday invitation (invitations) - Changeable age - Age invitations'
UNION ALL SELECT 'birthday-invitation-invitations-changeable-age-age-invitations-21-years', 'Birthday invitation (invitations) - Changeable age - Age invitations - 21 years'
UNION ALL SELECT 'birthday-invitation-invitations-changeable-age-age-invitations-30-years', 'Birthday invitation (invitations) - Changeable age - Age invitations - 30 years'
UNION ALL SELECT 'birthday-invitation-invitations-changeable-age-age-invitations-40-years', 'Birthday invitation (invitations) - Changeable age - Age invitations - 40 years'
UNION ALL SELECT 'birthday-invitation-invitations-changeable-age-age-invitations-50-years', 'Birthday invitation (invitations) - Changeable age - Age invitations - 50 years'
UNION ALL SELECT 'birthday-invitation-invitations-surprise-party', 'Birthday invitation (invitations) - Surprise party'
UNION ALL SELECT 'blue-monday', 'Blue Monday'
UNION ALL SELECT 'brother-and-sister-day', 'Brother and Sister day'
UNION ALL SELECT 'business-invitations-invitations', 'Business invitations (invitations)'
UNION ALL SELECT 'carnaval', 'Carnaval'
UNION ALL SELECT 'childrens-party-invitations', 'Childrens party (invitations)'
UNION ALL SELECT 'childrens-party-invitations-changeable-age-kids', 'Childrens party (invitations) - Changeable age kids'
UNION ALL SELECT 'childrens-party-invitations-first-childrensbirthday', 'Childrens party (invitations) - First childrensbirthday'
UNION ALL SELECT 'chinese-new-year', 'Chinese New Year'
UNION ALL SELECT 'christmas', 'Christmas'
UNION ALL SELECT 'christmas-christmas-birth', 'Christmas - Christmas birth'
UNION ALL SELECT 'christmas-christmas-birthday', 'Christmas - Christmas birthday'
UNION ALL SELECT 'christmas-christmas-humor', 'Christmas - Christmas humor'
UNION ALL SELECT 'christmas-christmas-in-the-weekend', 'Christmas - Christmas in the weekend'
UNION ALL SELECT 'christmas-christmas-most-sold', 'Christmas - Christmas most sold'
UNION ALL SELECT 'christmas-christmas-most-sold-christmas-humor', 'Christmas - Christmas most sold - Christmas humor'
UNION ALL SELECT 'christmas-christmas-most-sold-christmas-humor-christmas-in-the-weekend', 'Christmas - Christmas most sold - Christmas humor - Christmas in the weekend'
UNION ALL SELECT 'christmas-christmas-most-sold-christmas-thinking-of-you', 'Christmas - Christmas most sold - Christmas thinking of you'
UNION ALL SELECT 'christmas-christmas-new-home', 'Christmas - Christmas new home'
UNION ALL SELECT 'christmas-christmas-thank-you', 'Christmas - Christmas thank you'
UNION ALL SELECT 'christmas-christmas-thinking-of-you', 'Christmas - Christmas thinking of you'
UNION ALL SELECT 'christmas-invitations', 'Christmas (invitations)'
UNION ALL SELECT 'christmas-invitations-christmas-business-ia', 'Christmas (invitations) - Christmas Business (IA)'
UNION ALL SELECT 'communion', 'Communion'
UNION ALL SELECT 'condolence', 'Condolence'
UNION ALL SELECT 'condolence-condolence-pet', 'Condolence - Condolence pet'
UNION ALL SELECT 'condolence-condolence-with-text', 'Condolence - Condolence with text'
UNION ALL SELECT 'condolence-condolence-without-text', 'Condolence - Condolence without text'
UNION ALL SELECT 'condolence-yearday', 'Condolence - Yearday'
UNION ALL SELECT 'confirmation', 'Confirmation'
UNION ALL SELECT 'congratulations-card-and-gift', 'Congratulations (card and gift)'
UNION ALL SELECT 'day-of-caregiving', 'Day of caregiving'
UNION ALL SELECT 'day-of-the-animals', 'Day of the animals'
UNION ALL SELECT 'day-of-the-daycare', 'Day of the daycare'
UNION ALL SELECT 'dinner-party-en-drinks-invitations', 'Dinner party en drinks (invitations)'
UNION ALL SELECT 'dinner-party-en-drinks-invitations-borrel-invitation', 'Dinner party en drinks (invitations) - Borrel (invitation)'
UNION ALL SELECT 'easterpasen', 'Easter/Pasen'
UNION ALL SELECT 'eid-al-adha->-offerfeest', 'Eid al Adha > Offerfeest'
UNION ALL SELECT 'eid-mubarak--suikerfeest', 'Eid Mubarak * Suikerfeest'
UNION ALL SELECT 'exam-party-invitations', 'Exam party (invitations)'
UNION ALL SELECT 'failed', 'Failed'
UNION ALL SELECT 'failed-re-exam', 'Failed - re exam'
UNION ALL SELECT 'fathersday', 'Fathersday'
UNION ALL SELECT 'fathersday-fathersday-beercards', 'Fathersday - Fathersday beercards'
UNION ALL SELECT 'fathersday-fathersday-best-sold', 'Fathersday - Fathersday best sold'
UNION ALL SELECT 'fathersday-fathersday-best-sold-fathersday-thinking-of-you', 'Fathersday - Fathersday best sold - Fathersday thinking of you'
UNION ALL SELECT 'fathersday-fathersday-thinking-of-you', 'Fathersday - Fathersday thinking of you'
UNION ALL SELECT 'fathersday-first-father_s-day', 'Fathersday - First Father''s day'
UNION ALL SELECT 'four-days-marches', 'Four days marches'
UNION ALL SELECT 'friendship2', 'Friendship2'
UNION ALL SELECT 'garden-party-invitations', 'Garden party (invitations)'
UNION ALL SELECT 'gender-reveal-party-invitations', 'Gender reveal party (invitations)'
UNION ALL SELECT 'get-well', 'Get well'
UNION ALL SELECT 'get-well-broken-bones', 'Get well - Broken bones'
UNION ALL SELECT 'get-well-chronically-or-seriously-ill', 'Get well - Chronically or seriously ill'
UNION ALL SELECT 'get-well-get-well-welcome-home', 'Get well - Get well welcome home'
UNION ALL SELECT 'good-luck', 'Good luck'
UNION ALL SELECT 'graduation', 'Graduation'
UNION ALL SELECT 'graduation-boat-license', 'Graduation - boat license'
UNION ALL SELECT 'graduation-course-completed', 'Graduation - Course completed'
UNION ALL SELECT 'graduation-driving-license-extended', 'Graduation - Driving License extended'
UNION ALL SELECT 'graduation-driving-license-graduated', 'Graduation - Driving License graduated'
UNION ALL SELECT 'graduation-driving-license-graduated-driving-license-extended', 'Graduation - Driving License graduated - Driving License extended'
UNION ALL SELECT 'graduation-driving-license-graduated-graduated-high-school', 'Graduation - Driving License graduated - Graduated high school'
UNION ALL SELECT 'graduation-graduated-afgestudeerd', 'Graduation - Graduated afgestudeerd'
UNION ALL SELECT 'graduation-graduated-high-school', 'Graduation - Graduated high school'
UNION ALL SELECT 'graduation-graduated-propaedeutic-certificate', 'Graduation - Graduated Propaedeutic certificate'
UNION ALL SELECT 'grandparents-day', 'Grandparents day'
UNION ALL SELECT 'halloween', 'Halloween'
UNION ALL SELECT 'hanukkah', 'Hanukkah'
UNION ALL SELECT 'happy-pride', 'Happy Pride'
UNION ALL SELECT 'housewarming-invitations-cardhouse', 'Housewarming (invitations Cardhouse)'
UNION ALL SELECT 'international-boss-day', 'International boss day'
UNION ALL SELECT 'international-women_s-day', 'International Women''s Day'
UNION ALL SELECT 'just-because', 'Just because'
UNION ALL SELECT 'just-because-beautiful-moments', 'Just because - Beautiful moments'
UNION ALL SELECT 'kingsday', 'Kingsday'
UNION ALL SELECT 'kingsday-kingsday-birthday', 'Kingsday - Kingsday birthday'
UNION ALL SELECT 'love', 'Love'
UNION ALL SELECT 'love-anniversary-relationship', 'Love - Anniversary relationship'
UNION ALL SELECT 'marriage-anniversary-invitations', 'Marriage anniversary (invitations)'
UNION ALL SELECT 'marriage-anniversary-invitations-change-number', 'Marriage anniversary (invitations) - Change number'
UNION ALL SELECT 'marriage-anniversary-invitations-change-number-married-10-years', 'Marriage anniversary (invitations) - Change number - married 10 years'
UNION ALL SELECT 'marriage-anniversary-invitations-change-number-married-25-years', 'Marriage anniversary (invitations) - Change number - married 25 years'
UNION ALL SELECT 'marriage-anniversary-invitations-change-number-married-40-years', 'Marriage anniversary (invitations) - Change number - married 40 years'
UNION ALL SELECT 'marriage-anniversary-invitations-change-number-married-5-years', 'Marriage anniversary (invitations) - Change number - married 5 years'
UNION ALL SELECT 'marriage-anniversary-invitations-change-number-married-50-years', 'Marriage anniversary (invitations) - Change number - married 50 years'
UNION ALL SELECT 'marriage-anniversary-invitations-married-10-years', 'Marriage anniversary (invitations) - married 10 years'
UNION ALL SELECT 'marriage-anniversary-invitations-married-125-years', 'Marriage anniversary (invitations) - married 12.5 years'
UNION ALL SELECT 'marriage-anniversary-invitations-married-25-years', 'Marriage anniversary (invitations) - married 25 years'
UNION ALL SELECT 'marriage-anniversary-invitations-married-30-years', 'Marriage anniversary (invitations) - married 30 years'
UNION ALL SELECT 'marriage-anniversary-invitations-married-35-years', 'Marriage anniversary (invitations) - married 35 years'
UNION ALL SELECT 'marriage-anniversary-invitations-married-40-years', 'Marriage anniversary (invitations) - married 40 years'
UNION ALL SELECT 'marriage-anniversary-invitations-married-50-years', 'Marriage anniversary (invitations) - married 50 years'
UNION ALL SELECT 'milestone', 'Milestone'
UNION ALL SELECT 'milestones', 'Milestones'
UNION ALL SELECT 'mothersday', 'Mothersday'
UNION ALL SELECT 'mothersday-first-mothersday', 'Mothersday - First mothersday'
UNION ALL SELECT 'mothersday-mothersday-best-sold', 'Mothersday - Mothersday best sold'
UNION ALL SELECT 'mothersday-mothersday-distance', 'Mothersday - Mothersday distance'
UNION ALL SELECT 'mothersday-mothersday-thinking-of-you', 'Mothersday - Mothersday thinking of you'
UNION ALL SELECT 'moving-announcement--invitations', 'Moving announcement  (invitations)'
UNION ALL SELECT 'moving-announcement--invitations-housewarming-invitations', 'Moving announcement  (invitations) - Housewarming (invitations)'
UNION ALL SELECT 'moving-announcement--invitations-moving-announcement-christmas', 'Moving announcement  (invitations) - Moving announcement christmas'
UNION ALL SELECT 'moving-announcement--invitations-moving-invitations', 'Moving announcement  (invitations) - Moving (invitations)'
UNION ALL SELECT 'moving-announcement-invitations', 'Moving announcement (invitations)'
UNION ALL SELECT 'new-home', 'New home'
UNION ALL SELECT 'new-home-living-together', 'New home - Living together'
UNION ALL SELECT 'new-home-renovate', 'New home - Renovate'
UNION ALL SELECT 'new-job', 'New Job'
UNION ALL SELECT 'new-job-say-goodbye', 'New Job - Say goodbye'
UNION ALL SELECT 'new-job-to-welcome', 'New Job - To welcome'
UNION ALL SELECT 'new-year-party-invitations-cardhouse', 'New year party (invitations cardhouse)'
UNION ALL SELECT 'new-years-party-invitations', 'New Years Party (invitations)'
UNION ALL SELECT 'new-years-party-invitations-new-year_s-reception-business', 'New Years Party (invitations) - New Year''s reception business'
UNION ALL SELECT 'newyears', 'Newyears'
UNION ALL SELECT 'opening-new-business', 'Opening new business'
UNION ALL SELECT 'opening-new-business-invitations', 'Opening new business (invitations)'
UNION ALL SELECT 'partnerships', 'Partnerships'
UNION ALL SELECT 'photoself', 'Photoself'
UNION ALL SELECT 'pregnant', 'Pregnant'
UNION ALL SELECT 'pregnant-adoption', 'Pregnant - Adoption'
UNION ALL SELECT 'pregnant-extra-special', 'Pregnant - Extra special'
UNION ALL SELECT 'pregnant-maternity-leave', 'Pregnant - Maternity Leave'
UNION ALL SELECT 'pregnant-miscarriage', 'Pregnant - Miscarriage'
UNION ALL SELECT 'promotion-grandparentsday', 'Promotion Grandparentsday'
UNION ALL SELECT 'proud-of-you', 'Proud of you'
UNION ALL SELECT 'retirement', 'Retirement'
UNION ALL SELECT 'save-the-date-wedding-cards-only', 'Save the date (Wedding cards only)'
UNION ALL SELECT 'save-the-date-wedding-cards-only', 'Save the date (wedding cards only)'
UNION ALL SELECT 'secretaryday', 'Secretaryday'
UNION ALL SELECT 'sinterklaas', 'Sinterklaas'
UNION ALL SELECT 'sorry', 'Sorry'
UNION ALL SELECT 'swimming-diploma', 'Swimming diploma'
UNION ALL SELECT 'thank-you', 'Thank you'
UNION ALL SELECT 'thank-you-cards-invitations', 'Thank you cards (invitations)'
UNION ALL SELECT 'thank-you-thank-you-caretakers', 'Thank you - Thank you caretakers'
UNION ALL SELECT 'thank-you-thank-you-teacher', 'Thank you - Thank you teacher'
UNION ALL SELECT 'thanksgiving', 'Thanksgiving'
UNION ALL SELECT 'thinking-of-you', 'Thinking of you'
UNION ALL SELECT 'vacation', 'Vacation'
UNION ALL SELECT 'vacation-greetings-from', 'Vacation - Greetings from'
UNION ALL SELECT 'vacation-honeymoon', 'Vacation - Honeymoon'
UNION ALL SELECT 'vacation-summer-pictures', 'Vacation - Summer pictures'
UNION ALL SELECT 'vacation-travelling', 'Vacation - Travelling'
UNION ALL SELECT 'vacation-vacation-welcome-home', 'Vacation - Vacation welcome home'
UNION ALL SELECT 'valentine', 'Valentine'
UNION ALL SELECT 'valentine-valentine-best-sold', 'Valentine - Valentine best sold'
UNION ALL SELECT 'valentine-valentine-best-sold-valentine-online-dating', 'Valentine - Valentine best sold - Valentine online dating'
UNION ALL SELECT 'valentine-valentine-best-sold-valentine-single', 'Valentine - Valentine best sold - Valentine single'
UNION ALL SELECT 'valentine-valentine-best-sold-valentine-thinking-of-you', 'Valentine - Valentine best sold - Valentine thinking of you'
UNION ALL SELECT 'valentine-valentine-in-love', 'Valentine - Valentine In love'
UNION ALL SELECT 'valentine-valentine-in-love-valentine-best-sold', 'Valentine - Valentine In love - Valentine best sold'
UNION ALL SELECT 'valentine-valentine-in-love-valentine-loving', 'Valentine - Valentine In love - Valentine loving'
UNION ALL SELECT 'valentine-valentine-loving', 'Valentine - Valentine loving'
UNION ALL SELECT 'valentine-valentine-loving-valentine-best-sold', 'Valentine - Valentine loving - Valentine best sold'
UNION ALL SELECT 'valentine-valentine-online-dating', 'Valentine - Valentine online dating'
UNION ALL SELECT 'valentine-valentine-secret-love', 'Valentine - Valentine secret love'
UNION ALL SELECT 'valentine-valentine-secret-love-valentine-best-sold', 'Valentine - Valentine secret love - Valentine best sold'
UNION ALL SELECT 'valentine-valentine-single', 'Valentine - Valentine single'
UNION ALL SELECT 'valentine-valentine-thinking-of-you', 'Valentine - Valentine thinking of you'
UNION ALL SELECT 'wedding', 'Wedding'
UNION ALL SELECT 'wedding-divorce', 'Wedding - Divorce'
UNION ALL SELECT 'wedding-engaged', 'Wedding - Engaged'
UNION ALL SELECT 'wedding-engaged-wedding-anniversary-just-married', 'Wedding - Engaged - Wedding Anniversary - Just Married'
UNION ALL SELECT 'wedding-gay-marriage', 'Wedding - Gay marriage'
UNION ALL SELECT 'wedding-invitation-wedding', 'Wedding invitation (wedding)'
UNION ALL SELECT 'wedding-invitation-wedding', 'Wedding invitation (Wedding)'
UNION ALL SELECT 'wedding-invitation-wedding-save-our-date', 'Wedding invitation (Wedding) - Save our date'
UNION ALL SELECT 'wedding-just-married', 'Wedding - Just Married'
UNION ALL SELECT 'wedding-notice-of-marriage', 'Wedding - Notice of marriage'
UNION ALL SELECT 'wedding-registered-partnership', 'Wedding - Registered partnership'
UNION ALL SELECT 'wedding-wedding-anniversary', 'Wedding - Wedding Anniversary'
UNION ALL SELECT 'wedding-wedding-anniversary-just-married', 'Wedding - Wedding Anniversary - Just Married'
UNION ALL SELECT 'wedding-witness', 'Wedding - Witness'

-- 2022-07-22
UNION ALL SELECT 'newyearscards', 'Newyearscards'
UNION ALL SELECT 'keti-koti', 'Keti Koti'
UNION ALL SELECT 'christmas-newyear-cards', 'Christmas Newyear Cards'
UNION ALL SELECT 'summer-pictures', 'Summer Pictures'
UNION ALL SELECT 'newyearscards-newyear-new-home', 'Newyearscards - Newyear - New Home'
UNION ALL SELECT 'newyearscards-newyear-birth', 'Newyearscards - Newyear - Birth'
UNION ALL SELECT 'newyearscards-newyear-birthday', 'Newyearscards - Newyear - Birthday'
UNION ALL SELECT 'eid-al-adha--offerfeest', 'Eid Al Adha - Offerfeest'
UNION ALL SELECT 'promotion-summer', 'Promotion - Summer'
UNION ALL SELECT 'uncle-and-aunt-day', 'Uncle And Aunt Day'
UNION ALL SELECT 'world-friendship-day', 'World Friendship Day'
