CREATE VIEW greetz_to_mnpg_relations_view 
AS
SELECT 'B2B' AS Greetz_Name, 'b2b' AS MP_Code, 'B2B' AS MP_Name
UNION ALL SELECT 'Bonus dad', 'step-dad', 'Step Dad'
UNION ALL SELECT 'Boy', 'for-boys', 'For Boys'
UNION ALL SELECT 'Boy and girl', 'family', 'Family'
UNION ALL SELECT 'Boy general', 'for-boys', 'For Boys'
UNION ALL SELECT 'Boys', 'for-boys', 'For Boys'
UNION ALL SELECT 'Brother', 'brother', 'Brother'
UNION ALL SELECT 'Colleague', 'colleague', 'Colleague'
UNION ALL SELECT 'Daddy to be', 'daddy-to-be', 'Daddy To Be'
UNION ALL SELECT 'Daughter', 'daughter', 'Daughter'
UNION ALL SELECT 'Employee', 'colleague', 'Colleague'
UNION ALL SELECT 'Father', 'dad', 'Dad'
UNION ALL SELECT 'Father and mother', 'mum-and-dad', 'Mum And Dad'
UNION ALL SELECT 'Fathers', 'dad', 'Dad'
UNION ALL SELECT 'Friend man', 'friend', 'Friend'
UNION ALL SELECT 'Friend woman', 'friend', 'Friend'
UNION ALL SELECT 'Girl', 'for-girls', 'For Girls'
UNION ALL SELECT 'Girl general', 'for-girls', 'For Girls'
UNION ALL SELECT 'Girls', 'for-girls', 'For Girls'
UNION ALL SELECT 'Granddaughter', 'granddaughter', 'Granddaughter'
UNION ALL SELECT 'Grandfather', 'grandad', 'Grandad'
UNION ALL SELECT 'Grandmother', 'grandma', 'Grandma'
UNION ALL SELECT 'Grandparents (Card only)', 'grandparents', 'Grandparents'
UNION ALL SELECT 'Grandson', 'grandson', 'Grandson'
UNION ALL SELECT 'Men', 'for-him', 'For Him'
UNION ALL SELECT 'Men general', 'friend', 'Friend'
UNION ALL SELECT 'Mommy to be', 'mum-to-be', 'Mum To Be'
UNION ALL SELECT 'Mother', 'mum', 'Mum'
UNION ALL SELECT 'Mothers', 'mum', 'Mum'
UNION ALL SELECT 'Nephew', 'nephew', 'Nephew'
UNION ALL SELECT 'Neutral', 'non-relations', 'Non Relations'
UNION ALL SELECT 'Neutral Adult', 'non-relations', 'Non Relations'
UNION ALL SELECT 'Neutral Child', 'non-relations', 'Non Relations'
UNION ALL SELECT 'Other half man', 'partner', 'Partner'
UNION ALL SELECT 'Other half woman', 'partner', 'Partner'
UNION ALL SELECT 'Parents', 'parents', 'Parents'
UNION ALL SELECT 'Sister', 'sister', 'Sister'
UNION ALL SELECT 'Son', 'son', 'Son'
UNION ALL SELECT 'Uncle', 'uncle', 'Uncle'
UNION ALL SELECT 'Uniseks', 'uniseks', 'Uniseks'
UNION ALL SELECT 'Woman general', 'for-her', 'For Her'
UNION ALL SELECT 'Women', 'for-her', 'For Her'
UNION ALL SELECT 'Zakelijk1 (cards missions)', 'colleague', 'Colleague'
