CREATE VIEW greetz_to_mnpg_suppliers_view 
AS
SELECT 'Abacus Cards' AS 'entity_key', 'Abacus Cards' AS 'name'
UNION ALL SELECT 'Alex Sharp', 'Alex Sharp'
UNION ALL SELECT 'All the Best Cards', 'All the Best Cards'
UNION ALL SELECT 'All Things Banter', 'All Things Banter'
UNION ALL SELECT 'Andrew Thornton', 'Andrew Thornton'
UNION ALL SELECT 'Angela Chick', 'Angela Chick'
UNION ALL SELECT 'Anoela Cards', 'Anoela Cards'
UNION ALL SELECT 'Banter King', 'Banter King'
UNION ALL SELECT 'Beth Fletcher Illustration', 'Beth Fletcher Illustration'
UNION ALL SELECT 'Blond Amsterdam', 'Blond Amsterdam'
UNION ALL SELECT 'Bold and Bright', 'Bold and Bright'
UNION ALL SELECT 'Bouffants and Broken Hearts', 'Bouffants and Broken Hearts'
UNION ALL SELECT 'Brainbox Candy', 'Brainbox Candy'
UNION ALL SELECT 'Bright Spot', 'Bright Spot'
UNION ALL SELECT 'Carte Blanche', 'Carte Blanche'
UNION ALL SELECT 'Catchy Images', 'Catchy Images'
UNION ALL SELECT 'Celebration Nation', 'Celebration Nation'
UNION ALL SELECT 'Charly Clements', 'Charly Clements'
UNION ALL SELECT 'Cheeky Chops', 'Cheeky Chops'
UNION ALL SELECT 'Citrus Bunn Limited', 'Citrus Bunn Limited'
UNION ALL SELECT 'Corrin Strain', 'Corrin Strain'
UNION ALL SELECT 'Dalia Clark Design', 'Dalia Clark Design'
UNION ALL SELECT 'Dean Morris', 'Dean Morris'
UNION ALL SELECT 'Deckled Edge', 'Deckled Edge'
UNION ALL SELECT 'Dinky Rouge', 'Dinky Rouge'
UNION ALL SELECT 'Doodles by Ini', 'Doodles by Ini'
UNION ALL SELECT 'Dotty Black', 'Dotty Black'
UNION ALL SELECT 'Dromenjager', 'Dromenjager'
UNION ALL SELECT 'Emma Proctor Designs', 'Emma Proctor Designs'
UNION ALL SELECT 'Fabriekshuys', 'Fabriekshuys'
UNION ALL SELECT 'Felt Studios Ltd.', 'Felt Studios Ltd.'
UNION ALL SELECT 'Fiep Westendorp', 'Fiep Westendorp'
UNION ALL SELECT 'Filthy Sentiments', 'Filthy Sentiments'
UNION ALL SELECT 'Go La La', 'Go La La'
UNION ALL SELECT 'Greetz', 'Greetz'
UNION ALL SELECT 'Greetz - Designer Collections', 'Greetz - Designer Collections'
UNION ALL SELECT 'Greetz Freestyle', 'Greetz Freestyle'
UNION ALL SELECT 'Hello Munki', 'Hello Munki'
UNION ALL SELECT 'IKPAKJEIN', 'IKPAKJEIN'
UNION ALL SELECT 'Isabel Clarke (Izzy Likes to Doodle)', 'Isabel Clarke (Izzy Likes to Doodle)'
UNION ALL SELECT 'Jenny Seddon', 'Jenny Seddon'
UNION ALL SELECT 'Jerry Tapscott', 'Jerry Tapscott'
UNION ALL SELECT 'Jess Rose', 'Jess Rose'
UNION ALL SELECT 'Jewel Branding', 'Jewel Branding'
UNION ALL SELECT 'JJL Rights', 'JJL Rights'
UNION ALL SELECT 'Jolly Awesome', 'Jolly Awesome'
UNION ALL SELECT 'Karmuka', 'Karmuka'
UNION ALL SELECT 'Katie Abey Design', 'Katie Abey Design'
UNION ALL SELECT 'Katt Jones Hulafig', 'Katt Jones Hulafig'
UNION ALL SELECT 'Kbizz', 'Kbizz'
UNION ALL SELECT 'Kitchen of smiles', 'Kitchen of smiles'
UNION ALL SELECT 'Kitsch Noir', 'Kitsch Noir'
UNION ALL SELECT 'Klaas de Jong', 'Klaas de Jong'
UNION ALL SELECT 'Klara Hawkins', 'Klara Hawkins'
UNION ALL SELECT 'Kleine Twinkeltjes', 'Kleine Twinkeltjes'
UNION ALL SELECT 'Kleine Vlindervoetjes', 'Kleine Vlindervoetjes'
UNION ALL SELECT 'Last Lemon Productions Ltd', 'Last Lemon Productions Ltd'
UNION ALL SELECT 'Letters by Julia', 'Letters by Julia'
UNION ALL SELECT 'Lief Leven', 'Lief Leven'
UNION ALL SELECT 'Ling Design', 'Ling Design'
UNION ALL SELECT 'Luckz', 'Luckz'
UNION ALL SELECT 'Lucy Maggie', 'Lucy Maggie'
UNION ALL SELECT 'Lucy Pearce Designs', 'Lucy Pearce Designs'
UNION ALL SELECT 'Maartje Bodt', 'Maartje Bodt'
UNION ALL SELECT 'Make a Wish', 'Make a Wish'
UNION ALL SELECT 'Marieke Witke', 'Marieke Witke'
UNION ALL SELECT 'Melolelo', 'Melolelo'
UNION ALL SELECT 'Memelou', 'Memelou'
UNION ALL SELECT 'Milestone - Sophia Vesting Holding', 'Milestone - Sophia Vesting Holding'
UNION ALL SELECT 'Millicent Venton', 'Millicent Venton'
UNION ALL SELECT 'Moonpig', 'Moonpig'
UNION ALL SELECT 'Natalie Alex Designs', 'Natalie Alex Designs'
UNION ALL SELECT 'Neil Clark', 'Neil Clark'
UNION ALL SELECT 'Nicholson', 'Nicholson'
UNION ALL SELECT 'Okey Dokey Design', 'Okey Dokey Design'
UNION ALL SELECT 'Orange Licensing BV', 'Orange Licensing BV'
UNION ALL SELECT 'Papagrazi Limited', 'Papagrazi Limited'
UNION ALL SELECT 'Paperclip', 'Paperclip'
UNION ALL SELECT 'Paperlink', 'Paperlink'
UNION ALL SELECT 'Pearl Ivy', 'Pearl Ivy'
UNION ALL SELECT 'Petit Konijn', 'Petit Konijn'
UNION ALL SELECT 'Photoflash', 'Photoflash'
UNION ALL SELECT 'Pigment Productions Ltd.', 'Pigment Productions Ltd.'
UNION ALL SELECT 'Playful Indian', 'Playful Indian'
UNION ALL SELECT 'Poet and painter', 'Poet and painter'
UNION ALL SELECT 'Redback Cards Limited', 'Redback Cards Limited'
UNION ALL SELECT 'Rumble Cards', 'Rumble Cards'
UNION ALL SELECT 'SADLER JONES LTD', 'SADLER JONES LTD'
UNION ALL SELECT 'Sooshichaha', 'Sooshichaha'
UNION ALL SELECT 'Stella Isaac Illustration', 'Stella Isaac Illustration'
UNION ALL SELECT 'Stichting Jarige Job', 'Stichting Jarige Job'
UNION ALL SELECT 'Stichting Vrienden van Loesje', 'Stichting Vrienden van Loesje'
UNION ALL SELECT 'Studio Pets', 'Studio Pets'
UNION ALL SELECT 'Tante Kaartje', 'Tante Kaartje'
UNION ALL SELECT 'Test test', 'Test test'
UNION ALL SELECT 'The Cardy Club', 'The Cardy Club'
UNION ALL SELECT 'The Studio of Mr & Mrs Downing', 'The Studio of Mr & Mrs Downing'
UNION ALL SELECT 'TheDogsDoodahs.com', 'TheDogsDoodahs.com'
UNION ALL SELECT 'TMS', 'TMS'
UNION ALL SELECT 'Tsjip', 'Tsjip'
UNION ALL SELECT 'UK Greetings', 'UK Greetings'
UNION ALL SELECT 'YH Tekent', 'YH Tekent'
