CREATE OR REPLACE TABLE "tmp_dm_envelope_names" (
	code VARCHAR(300) NOT NULL,
	name VARCHAR(300) NOT NULL,
	PRIMARY KEY (code)
)
--COLLATE='utf8_bin'
;
-- select * from "tmp_dm_envelope_names"
-- drop table "tmp_dm_envelope_names"


INSERT INTO "tmp_dm_envelope_names"
SELECT 'envelope_evd_standard_medium_fizz_lime_windowed', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_evd_standard_xxl_fizz_lime_windowed', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_evd_standard_supersize_fizz_lime_windowed', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_evd_square_large_fizz_lime_windowed', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_evd_square_xxl_fizz_lime_windowed', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_evd_square_supersize_fizz_lime_windowed', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_birth_square_large_metallic_white_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_birth_square_large_metallic_platinum_withoutwindow', 'Envelop'
UNION ALL SELECT 'birth_envelope_Square_Large_Pressed_Off_White', 'Envelop'
UNION ALL SELECT 'birth_envelope_Square_Large_Pressed_Blue', 'Envelop'
UNION ALL SELECT 'birth_envelope_Square_Large_Pressed_Pink', 'Envelop'
UNION ALL SELECT 'birth_envelope_Square_Large_Pressed_Red', 'Envelop'
UNION ALL SELECT 'birth_envelope_Square_Large_Pressed_Lime', 'Envelop'
UNION ALL SELECT 'birth_envelope_Square_Large_Pressed_Orange', 'Envelop'
UNION ALL SELECT 'envelope_birth_square_large_roma_light_blue_withoutwindow', 'Envelop licht blauw'
UNION ALL SELECT 'envelope_birth_square_large_roma_light_pink_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_birth_square_large_roma_bright_pink_withoutwindow', 'Envelop fuchsia'
UNION ALL SELECT 'envelope_birth_square_large_roma_bright_orange_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_birth_square_large_roma_bright_red_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_birth_square_large_roma_biotop_withoutwindow', 'Envelop off-white'
UNION ALL SELECT 'envelope_birth_square_large_roma_ocean_blue_withoutwindow', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_birth_square_large_roma_apple_green_withoutwindow', 'Envelop groen'
UNION ALL SELECT 'envelope_evd_standard_medium_fizz_white_windowed', 'Envelop helder wit'
UNION ALL SELECT 'envelope_evd_standard_xxl_fizz_white_windowed', 'Envelop helder wit'
UNION ALL SELECT 'envelope_evd_standard_xxl_fizz_bright_pink_windowed', 'Envelop knal roze'
UNION ALL SELECT 'envelope_evd_standard_xxl_fizz_blue_windowed', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_evd_standard_xxl_fizz_dark_red_windowed', 'Envelop diep rood'
UNION ALL SELECT 'envelope_evd_standard_xxl_fizz_dark_orange_windowed', 'Envelop fris oranje'
UNION ALL SELECT 'envelope_evd_standard_xxl_fizz_bright_yellow_windowed', 'Envelop vrolijk geel'
UNION ALL SELECT 'envelope_evd_standard_xxl_fizz_dark_purple_windowed', 'Envelop chique paarse'
UNION ALL SELECT 'envelope_evd_standard_xxl_fizz_grey_windowed', 'Envelop stijlvol grijs'
UNION ALL SELECT 'envelope_evd_standard_xxl_fizz_black_windowed', 'Envelop echt zwart'
UNION ALL SELECT 'envelope_evd_standard_supersize_fizz_white_windowed', 'Envelop helder wit'
UNION ALL SELECT 'envelope_evd_standard_supersize_fizz_bright_pink_windowed', 'Envelop knal roze'
UNION ALL SELECT 'envelope_evd_standard_supersize_fizz_blue_windowed', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_evd_standard_supersize_fizz_dark_red_windowed', 'Envelop diep rood'
UNION ALL SELECT 'envelope_evd_standard_supersize_fizz_dark_orange_windowed', 'Envelop fris oranje'
UNION ALL SELECT 'envelope_evd_standard_supersize_fizz_bright_yellow_windowed', 'Envelop vrolijk geel'
UNION ALL SELECT 'envelope_evd_standard_supersize_fizz_dark_purple_windowed', 'Envelop chique paarse'
UNION ALL SELECT 'envelope_evd_standard_supersize_fizz_grey_windowed', 'Envelop stijlvol grijs'
UNION ALL SELECT 'envelope_evd_standard_supersize_fizz_black_windowed', 'Envelop echt zwart'
UNION ALL SELECT 'envelope_evd_square_large_fizz_white_windowed', 'Envelop helder wit'
UNION ALL SELECT 'envelope_evd_square_xxl_fizz_white_windowed', 'Envelop helder wit'
UNION ALL SELECT 'envelope_evd_square_xxl_fizz_bright_pink_windowed', 'Envelop knal roze'
UNION ALL SELECT 'envelope_evd_square_xxl_fizz_blue_windowed', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_evd_square_xxl_fizz_dark_red_windowed', 'Envelop diep rood'
UNION ALL SELECT 'envelope_evd_square_xxl_fizz_dark_orange_windowed', 'Envelop fris oranje'
UNION ALL SELECT 'envelope_evd_square_xxl_fizz_bright_yellow_windowed', 'Envelop vrolijk geel'
UNION ALL SELECT 'envelope_evd_square_xxl_fizz_dark_purple_windowed', 'Envelop chique paarse'
UNION ALL SELECT 'envelope_evd_square_xxl_fizz_grey_windowed', 'Envelop stijlvol grijs'
UNION ALL SELECT 'envelope_evd_square_xxl_fizz_black_windowed', 'Envelop echt zwart'
UNION ALL SELECT 'envelope_evd_square_supersize_fizz_white_windowed', 'Envelop helder wit'
UNION ALL SELECT 'envelope_evd_square_supersize_fizz_bright_pink_windowed', 'Envelop knal roze'
UNION ALL SELECT 'envelope_evd_square_supersize_fizz_blue_windowed', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_evd_square_supersize_fizz_dark_red_windowed', 'Envelop diep rood'
UNION ALL SELECT 'envelope_evd_square_supersize_fizz_dark_orange_windowed', 'Envelop fris oranje'
UNION ALL SELECT 'envelope_evd_square_supersize_fizz_bright_yellow_windowed', 'Envelop vrolijk geel'
UNION ALL SELECT 'envelope_evd_square_supersize_fizz_dark_purple_windowed', 'Envelop chique paarse'
UNION ALL SELECT 'envelope_evd_square_supersize_fizz_grey_windowed', 'Envelop stijlvol grijs'
UNION ALL SELECT 'envelope_evd_square_supersize_fizz_black_windowed', 'Envelop echt zwart'
UNION ALL SELECT 'envelope_evd_standard_medium_fizz_dark_red_windowed', 'Envelop diep rood'
UNION ALL SELECT 'envelope_evd_square_large_fizz_dark_red_windowed', 'Envelop diep rood'
UNION ALL SELECT 'birth_envelope_Slim_Medium_Bright_Red', 'Envelop'
UNION ALL SELECT 'birth_envelope_Slim_Small_Pressed_Blue', 'Envelop'
UNION ALL SELECT 'birth_envelope_Slim_Small_Light_Blue', 'Envelop licht blauw'
UNION ALL SELECT 'birth_envelope_Slim_Small_Bright_Pink', 'Envelop fuchsia'
UNION ALL SELECT 'birth_envelope_Slim_Small_Apple_Green', 'Envelop groen'
UNION ALL SELECT 'birth_envelope_Square_Small_Pressed_Pink', 'Envelop'
UNION ALL SELECT 'birth_envelope_Square_Small_Pressed_Lime', 'Envelop'
UNION ALL SELECT 'envelope_birth_square_small_roma_light_blue_withoutwindow', 'Envelop licht blauw'
UNION ALL SELECT 'birth_envelope_Oblong_Medium_Pressed_Blue', 'Envelop'
UNION ALL SELECT 'birth_envelope_Oblong_Medium_Pressed_Red', 'Envelop'
UNION ALL SELECT 'envelope_birth_standard_medium_roma_light_blue_withoutwindow', 'Envelop licht blauw'
UNION ALL SELECT 'birth_envelope_Oblong_Medium_Pressed_Orange', 'Envelop'
UNION ALL SELECT 'envelope_birth_standard_medium_roma_bright_orange_withoutwindow', 'Envelop'
UNION ALL SELECT 'birth_envelope_Oblong_Small_Pressed_Orange', 'Envelop'
UNION ALL SELECT 'envelope_birth_standard_small_roma_light_pink_withoutwindow', 'Envelop licht roze'
UNION ALL SELECT 'envelope_birth_standard_small_roma_bright_orange_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_birth_standard_small_roma_bright_red_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_birth_standard_small_roma_ocean_blue_withoutwindow', 'Envelop oceaan blauw'
UNION ALL SELECT 'birth_envelope_Slim_Medium_Pressed_Off_White', 'Envelop wit'
UNION ALL SELECT 'birth_envelope_Slim_Medium_Pressed_Red', 'Envelop'
UNION ALL SELECT 'birth_envelope_Slim_Medium_Light_Blue', 'Envelop licht blauw'
UNION ALL SELECT 'birth_envelope_Slim_Medium_Bright_Pink', 'Envelop fuchsia'
UNION ALL SELECT 'birth_envelope_Slim_Medium_Ocean_Blue', 'Envelop oceaan blauw'
UNION ALL SELECT 'birth_envelope_Slim_Medium_Apple_Green', 'Envelop groen'
UNION ALL SELECT 'birth_envelope_Slim_Small_Metallic_White', 'Envelop wit'
UNION ALL SELECT 'birth_envelope_Slim_Small_Metallic_Platinum', 'Envelop'
UNION ALL SELECT 'birth_envelope_Slim_Small_Pressed_Lime', 'Envelop'
UNION ALL SELECT 'birth_envelope_Slim_Small_Light_Pink', 'Envelop licht roze'
UNION ALL SELECT 'birth_envelope_Slim_Small_Bright_Orange', 'Envelop'
UNION ALL SELECT 'birth_envelope_Slim_Small_Bright_Red', 'Envelop'
UNION ALL SELECT 'birth_envelope_Slim_Small_Biotop', 'Envelop off-white'
UNION ALL SELECT 'birth_envelope_Slim_Small_Ocean_Blue', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_birth_square_small_metallic_white_withoutwindow', 'Envelop wit'
UNION ALL SELECT 'birth_envelope_Square_Small_Pressed_Blue', 'Envelop'
UNION ALL SELECT 'birth_envelope_Square_Small_Pressed_Red', 'Envelop'
UNION ALL SELECT 'envelope_birth_square_small_roma_bright_orange_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_birth_square_small_roma_biotop_withoutwindow', 'Envelop off-white'
UNION ALL SELECT 'envelope_birth_standard_medium_metallic_white_withoutwindow', 'Envelop wit'
UNION ALL SELECT 'birth_envelope_Square_Small_Pressed_Off_White', 'Envelop wit'
UNION ALL SELECT 'birth_envelope_Square_Small_Pressed_Orange', 'Envelop'
UNION ALL SELECT 'envelope_birth_square_small_roma_light_pink_withoutwindow', 'Envelop licht roze'
UNION ALL SELECT 'envelope_birth_square_small_roma_ocean_blue_withoutwindow', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_birth_square_small_roma_apple_green_withoutwindow', 'Envelop groen'
UNION ALL SELECT 'birth_envelope_Oblong_Medium_Pressed_Off_White', 'Envelop wit'
UNION ALL SELECT 'birth_envelope_Oblong_Medium_Pressed_Lime', 'Envelop'
UNION ALL SELECT 'birth_envelope_Oblong_Small_Pressed_Blue', 'Envelop'
UNION ALL SELECT 'envelope_birth_standard_small_roma_light_blue_withoutwindow', 'Envelop licht blauw'
UNION ALL SELECT 'birth_envelope_Slim_Medium_Pressed_Blue', 'Envelop'
UNION ALL SELECT 'birth_envelope_Slim_Medium_Pressed_Lime', 'Envelop'
UNION ALL SELECT 'birth_envelope_Slim_Medium_Light_Pink', 'Envelop licht roze'
UNION ALL SELECT 'birth_envelope_Slim_Medium_Biotop', 'Envelop off-white'
UNION ALL SELECT 'birth_envelope_Slim_Small_Pressed_Off_White', 'Envelop wit'
UNION ALL SELECT 'birth_envelope_Slim_Small_Pressed_Pink', 'Envelop'
UNION ALL SELECT 'birth_envelope_Slim_Small_Pressed_Red', 'Envelop'
UNION ALL SELECT 'birth_envelope_Slim_Small_Pressed_Orange', 'Envelop'
UNION ALL SELECT 'birth_envelope_Slim_Medium_Metallic_White', 'Envelop wit'
UNION ALL SELECT 'envelope_birth_square_small_metallic_platinum_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_birth_square_small_roma_bright_pink_withoutwindow', 'Envelop fuchsia'
UNION ALL SELECT 'envelope_birth_square_small_roma_bright_red_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_birth_standard_medium_metallic_platinum_withoutwindow', 'Envelop'
UNION ALL SELECT 'birth_envelope_Oblong_Medium_Pressed_Pink', 'Envelop'
UNION ALL SELECT 'envelope_birth_standard_medium_roma_light_pink_withoutwindow', 'Envelop licht roze'
UNION ALL SELECT 'envelope_birth_standard_medium_roma_bright_pink_withoutwindow', 'Envelop fuchsia'
UNION ALL SELECT 'envelope_birth_standard_medium_roma_bright_red_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_birth_standard_medium_roma_biotop_withoutwindow', 'Envelop off-white'
UNION ALL SELECT 'envelope_birth_standard_medium_roma_ocean_blue_withoutwindow', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_birth_standard_medium_roma_apple_green_withoutwindow', 'Envelop groen'
UNION ALL SELECT 'envelope_birth_standard_small_metallic_white_withoutwindow', 'Envelop wit'
UNION ALL SELECT 'envelope_birth_standard_small_metallic_platinum_withoutwindow', 'Envelop'
UNION ALL SELECT 'birth_envelope_Oblong_Small_Pressed_Off_White', 'Envelop wit'
UNION ALL SELECT 'birth_envelope_Oblong_Small_Pressed_Pink', 'Envelop'
UNION ALL SELECT 'birth_envelope_Oblong_Small_Pressed_Red', 'Envelop'
UNION ALL SELECT 'birth_envelope_Oblong_Small_Pressed_Lime', 'Envelop'
UNION ALL SELECT 'envelope_birth_standard_small_roma_bright_pink_withoutwindow', 'Envelop fuchsia'
UNION ALL SELECT 'envelope_birth_standard_small_roma_biotop_withoutwindow', 'Envelop off-white'
UNION ALL SELECT 'envelope_birth_standard_small_roma_apple_green_withoutwindow', 'Envelop groen'
UNION ALL SELECT 'birth_envelope_Slim_Medium_Metallic_Platinum', 'Envelop'
UNION ALL SELECT 'birth_envelope_Slim_Medium_Pressed_Pink', 'Envelop'
UNION ALL SELECT 'birth_envelope_Slim_Medium_Pressed_Orange', 'Envelop'
UNION ALL SELECT 'birth_envelope_Slim_Medium_Bright_Orange', 'Envelop'
UNION ALL SELECT 'envelope_evd_standard_medium_fizz_white_withoutwindow', 'Envelop helder wit'
UNION ALL SELECT 'envelope_evd_standard_xl_fizz_white_withoutwindow', 'Envelop helder wit'
UNION ALL SELECT 'envelope_evd_standard_medium_fizz_lime_withoutwindow', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_evd_standard_xxl_fizz_lime_withoutwindow', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_evd_standard_xxl_fizz_white_withoutwindow', 'Envelop helder wit'
UNION ALL SELECT 'envelope_evd_standard_xxl_fizz_bright_pink_withoutwindow', 'Envelop knal roze'
UNION ALL SELECT 'envelope_evd_standard_xxl_fizz_blue_withoutwindow', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_evd_standard_xxl_fizz_dark_red_withoutwindow', 'Envelop diep rood'
UNION ALL SELECT 'envelope_evd_standard_xxl_fizz_dark_orange_withoutwindow', 'Envelop fris oranje'
UNION ALL SELECT 'envelope_evd_standard_xxl_fizz_bright_yellow_withoutwindow', 'Envelop vrolijk geel'
UNION ALL SELECT 'envelope_evd_standard_xxl_fizz_dark_purple_withoutwindow', 'Envelop chique paarse'
UNION ALL SELECT 'envelope_evd_standard_xxl_fizz_grey_withoutwindow', 'Envelop stijlvol grijs'
UNION ALL SELECT 'envelope_evd_standard_xxl_fizz_black_withoutwindow', 'Envelop echt zwart'
UNION ALL SELECT 'envelope_evd_standard_supersize_fizz_lime_withoutwindow', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_evd_standard_supersize_fizz_white_withoutwindow', 'Envelop helder wit'
UNION ALL SELECT 'envelope_evd_standard_supersize_fizz_bright_pink_withoutwindow', 'Envelop knal roze'
UNION ALL SELECT 'envelope_evd_standard_supersize_fizz_blue_withoutwindow', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_evd_standard_supersize_fizz_dark_red_withoutwindow', 'Envelop diep rood'
UNION ALL SELECT 'envelope_evd_standard_supersize_fizz_dark_orange_withoutwindow', 'Envelop fris oranje'
UNION ALL SELECT 'envelope_evd_standard_supersize_fizz_bright_yellow_withoutwindow', 'Envelop vrolijk geel'
UNION ALL SELECT 'envelope_evd_standard_supersize_fizz_dark_purple_withoutwindow', 'Envelop chique paarse'
UNION ALL SELECT 'envelope_evd_standard_supersize_fizz_grey_withoutwindow', 'Envelop stijlvol grijs'
UNION ALL SELECT 'envelope_evd_standard_supersize_fizz_black_withoutwindow', 'Envelop echt zwart'
UNION ALL SELECT 'envelope_evd_square_large_fizz_lime_withoutwindow', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_evd_square_large_fizz_white_withoutwindow', 'Envelop helder wit'
UNION ALL SELECT 'envelope_evd_square_xxl_fizz_lime_withoutwindow', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_evd_square_xxl_fizz_white_withoutwindow', 'Envelop helder wit'
UNION ALL SELECT 'envelope_evd_square_xxl_fizz_bright_pink_withoutwindow', 'Envelop knal roze'
UNION ALL SELECT 'envelope_evd_square_xxl_fizz_blue_withoutwindow', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_evd_square_xxl_fizz_dark_red_withoutwindow', 'Envelop diep rood'
UNION ALL SELECT 'envelope_evd_square_xxl_fizz_dark_orange_withoutwindow', 'Envelop fris oranje'
UNION ALL SELECT 'envelope_evd_square_xxl_fizz_bright_yellow_withoutwindow', 'Envelop vrolijk geel'
UNION ALL SELECT 'envelope_evd_square_xxl_fizz_dark_purple_withoutwindow', 'Envelop chique paarse'
UNION ALL SELECT 'envelope_evd_square_xxl_fizz_grey_withoutwindow', 'Envelop stijlvol grijs'
UNION ALL SELECT 'envelope_evd_square_xxl_fizz_black_withoutwindow', 'Envelop echt zwart'
UNION ALL SELECT 'envelope_evd_square_supersize_fizz_lime_withoutwindow', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_evd_square_supersize_fizz_white_withoutwindow', 'Envelop helder wit'
UNION ALL SELECT 'envelope_evd_square_supersize_fizz_bright_pink_withoutwindow', 'Envelop knal roze'
UNION ALL SELECT 'envelope_evd_square_supersize_fizz_blue_withoutwindow', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_evd_square_supersize_fizz_dark_red_withoutwindow', 'Envelop diep rood'
UNION ALL SELECT 'envelope_evd_square_supersize_fizz_dark_orange_withoutwindow', 'Envelop fris oranje'
UNION ALL SELECT 'envelope_evd_square_supersize_fizz_bright_yellow_withoutwindow', 'Envelop vrolijk geel'
UNION ALL SELECT 'envelope_evd_square_supersize_fizz_dark_purple_withoutwindow', 'Envelop chique paarse'
UNION ALL SELECT 'envelope_evd_square_supersize_fizz_grey_withoutwindow', 'Envelop stijlvol grijs'
UNION ALL SELECT 'envelope_evd_square_supersize_fizz_black_withoutwindow', 'Envelop echt zwart'
UNION ALL SELECT 'envelope_gifts_Square_Large', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_evd_square_large_fizz_dark_red_withoutwindow', 'Envelop diep rood'
UNION ALL SELECT 'envelope_gifts_Square_Large_Fizz_White', 'Envelop helder wit'
UNION ALL SELECT 'envelope_gifts_Square_SuperSize', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_gifts_Square_Supersize_Fizz_Black', 'Envelop echt zwart'
UNION ALL SELECT 'envelope_gifts_Square_Supersize_Fizz_Blue', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_gifts_Square_Supersize_Fizz_Bright_Pink', 'Envelop knal roze'
UNION ALL SELECT 'envelope_gifts_Square_Supersize_Fizz_Bright_Yellow', 'Envelop vrolijk geel'
UNION ALL SELECT 'envelope_gifts_Square_Supersize_Fizz_Dark_Orange', 'Envelop fris oranje'
UNION ALL SELECT 'envelope_gifts_Square_Supersize_Fizz_Dark_Purple', 'Envelop chique paarse'
UNION ALL SELECT 'envelope_gifts_Square_Supersize_Fizz_Dark_Red', 'Envelop diep rood'
UNION ALL SELECT 'envelope_gifts_Square_Supersize_Fizz_Grey', 'Envelop stijlvol grijs'
UNION ALL SELECT 'envelope_gifts_Square_Supersize_Fizz_White', 'Envelop helder wit'
UNION ALL SELECT 'envelope_gifts_Square_XXL', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_gifts_Square_XXL_Fizz_Black', 'Envelop echt zwart'
UNION ALL SELECT 'envelope_gifts_Square_XXL_Fizz_Blue', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_gifts_Square_XXL_Fizz_Bright_Pink', 'Envelop knal roze'
UNION ALL SELECT 'envelope_gifts_Square_XXL_Fizz_Bright_Yellow', 'Envelop vrolijk geel'
UNION ALL SELECT 'envelope_gifts_Square_XXL_Fizz_Dark_Orange', 'Envelop fris oranje'
UNION ALL SELECT 'envelope_gifts_Square_XXL_Fizz_Dark_Purple', 'Envelop chique paarse'
UNION ALL SELECT 'envelope_gifts_Square_XXL_Fizz_Dark_Red', 'Envelop diep rood'
UNION ALL SELECT 'envelope_gifts_Square_XXL_Fizz_Grey', 'Envelop stijlvol grijs'
UNION ALL SELECT 'envelope_gifts_Square_XXL_Fizz_White', 'Envelop helder wit'
UNION ALL SELECT 'envelope_gifts_Standard_Medium', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_evd_standard_medium_fizz_dark_red_withoutwindow', 'Envelop diep rood'
UNION ALL SELECT 'envelope_gifts_Standard_Medium_Fizz_White', 'Envelop helder wit'
UNION ALL SELECT 'envelope_gifts_Standard_Supersize', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_gifts_Standard_Supersize_Fizz_Black', 'Envelop echt zwart'
UNION ALL SELECT 'envelope_gifts_Standard_Supersize_Fizz_Blue', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_gifts_Standard_Supersize_Fizz_Bright_Pink', 'Envelop knal roze'
UNION ALL SELECT 'envelope_gifts_Standard_Supersize_Fizz_Bright_Yellow', 'Envelop vrolijk geel'
UNION ALL SELECT 'envelope_gifts_Standard_Supersize_Fizz_Dark_Orange', 'Envelop fris oranje'
UNION ALL SELECT 'envelope_gifts_Standard_Supersize_Fizz_Dark_Purple', 'Envelop chique paarse'
UNION ALL SELECT 'envelope_gifts_Standard_Supersize_Fizz_Dark_Red', 'Envelop diep rood'
UNION ALL SELECT 'envelope_gifts_Standard_Supersize_Fizz_Grey', 'Envelop stijlvol grijs'
UNION ALL SELECT 'envelope_gifts_Standard_Supersize_Fizz_White', 'Envelop helder wit'
UNION ALL SELECT 'envelope_gifts_Standard_XXL', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_gifts_Standard_XXL_Fizz_Black', 'Envelop echt zwart'
UNION ALL SELECT 'envelope_gifts_Standard_XXL_Fizz_Blue', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_gifts_Standard_XXL_Fizz_Bright_Pink', 'Envelop knal roze'
UNION ALL SELECT 'envelope_gifts_Standard_XXL_Fizz_Bright_Yellow', 'Envelop vrolijk geel'
UNION ALL SELECT 'envelope_gifts_Standard_XXL_Fizz_Dark_Orange', 'Envelop fris oranje'
UNION ALL SELECT 'envelope_gifts_Standard_XXL_Fizz_Dark_Purple', 'Envelop chique paarse'
UNION ALL SELECT 'envelope_gifts_Standard_XXL_Fizz_Dark_Red', 'Envelop diep rood'
UNION ALL SELECT 'envelope_gifts_Standard_XXL_Fizz_Grey', 'Envelop stijlvol grijs'
UNION ALL SELECT 'envelope_gifts_Standard_XXL_Fizz_White', 'Envelop helder wit'
UNION ALL SELECT 'envelope_evd_standard_mini_fizz_white_withoutwindow', 'Envelop helder wit'
UNION ALL SELECT 'envelope_evd_standard_mini_fizz_white_windowed', 'Envelop helder wit'
UNION ALL SELECT 'envelope_evd_standard_medium_fizz_bright_pink_windowed', 'Envelop knal roze'
UNION ALL SELECT 'envelope_evd_standard_medium_fizz_blue_windowed', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_standard_medium_2p_fizz_dark_red', 'Envelop diep rood'
UNION ALL SELECT 'envelope_evd_square_large_fizz_bright_pink_windowed', 'Envelop knal roze'
UNION ALL SELECT 'envelope_evd_square_large_fizz_blue_windowed', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_square_large_2p_fizz_dark_red', 'Envelop diep rood'
UNION ALL SELECT 'envelope_evd_standard_medium_fizz_bright_pink_withoutwindow', 'Envelop knal roze'
UNION ALL SELECT 'envelope_evd_standard_medium_fizz_blue_withoutwindow', 'Envelop oceaan blauw'
UNION ALL SELECT 'packaging_gift_cardboard_envelope_standard_medium_2p_fizz_dark_red', 'Envelop diep rood'
UNION ALL SELECT 'envelope_evd_square_large_fizz_bright_pink_withoutwindow', 'Envelop knal roze'
UNION ALL SELECT 'envelope_evd_square_large_fizz_blue_withoutwindow', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_evd_standard_medium_paperlynx_gold_windowed', 'Envelop'
UNION ALL SELECT 'envelope_evd_standard_medium_paperlynx_silver_windowed', 'Envelop'
UNION ALL SELECT 'envelope_evd_square_large_paperlynx_gold_windowed', 'Envelop'
UNION ALL SELECT 'envelope_evd_square_large_paperlynx_silver_windowed', 'Envelop'
UNION ALL SELECT 'envelope_evd_standard_medium_paperlynx_gold_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_evd_standard_medium_paperlynx_silver_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_evd_square_large_paperlynx_gold_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_evd_square_large_paperlynx_silver_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_evd_square_large_fizz_grey_withoutwindow', 'Envelop stijlvol grijs'
UNION ALL SELECT 'envelope_wedding_square_large_metallic_white_withoutwindow', 'Envelop wit'
UNION ALL SELECT 'envelope_wedding_square_large_metallic_platinum_withoutwindow', 'Envelop'
UNION ALL SELECT 'wedding_envelope_Square_Large_Pressed_Off_White', 'Envelop wit'
UNION ALL SELECT 'wedding_envelope_Square_Large_Pressed_Blue', 'Envelop'
UNION ALL SELECT 'wedding_envelope_Square_Large_Pressed_Pink', 'Envelop'
UNION ALL SELECT 'wedding_envelope_Square_Large_Pressed_Red', 'Envelop'
UNION ALL SELECT 'wedding_envelope_Square_Large_Pressed_Lime', 'Envelop'
UNION ALL SELECT 'wedding_envelope_Square_Large_Pressed_Orange', 'Envelop'
UNION ALL SELECT 'envelope_wedding_square_large_roma_light_blue_withoutwindow', 'Envelop licht blauw'
UNION ALL SELECT 'envelope_wedding_square_large_roma_light_pink_withoutwindow', 'Envelop licht roze'
UNION ALL SELECT 'envelope_wedding_square_large_roma_bright_pink_withoutwindow', 'Envelop fuchsia'
UNION ALL SELECT 'envelope_wedding_square_large_roma_bright_orange_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_wedding_square_large_roma_bright_red_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_wedding_square_large_roma_biotop_withoutwindow', 'Envelop off-white'
UNION ALL SELECT 'envelope_wedding_square_large_roma_ocean_blue_withoutwindow', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_wedding_square_large_roma_apple_green_withoutwindow', 'Envelop groen'
UNION ALL SELECT 'wedding_envelope_Slim_Medium_Bright_Red', 'Envelop'
UNION ALL SELECT 'wedding_envelope_Oblong_Medium_Pressed_Blue', 'Envelop'
UNION ALL SELECT 'wedding_envelope_Oblong_Medium_Pressed_Red', 'Envelop'
UNION ALL SELECT 'envelope_wedding_standard_medium_roma_light_blue_withoutwindow', 'Envelop licht blauw'
UNION ALL SELECT 'wedding_envelope_Oblong_Medium_Pressed_Orange', 'Envelop'
UNION ALL SELECT 'envelope_wedding_standard_medium_roma_bright_orange_withoutwindow', 'Envelop'
UNION ALL SELECT 'wedding_envelope_Slim_Medium_Pressed_Red', 'Envelop'
UNION ALL SELECT 'wedding_envelope_Slim_Medium_Light_Blue', 'Envelop licht blauw'
UNION ALL SELECT 'wedding_envelope_Slim_Medium_Bright_Pink', 'Envelop fuchsia'
UNION ALL SELECT 'wedding_envelope_Slim_Medium_Ocean_Blue', 'Envelop oceaan blauw'
UNION ALL SELECT 'wedding_envelope_Slim_Medium_Apple_Green', 'Envelop groen'
UNION ALL SELECT 'envelope_wedding_standard_medium_metallic_white_withoutwindow', 'Envelop wit'
UNION ALL SELECT 'wedding_envelope_Oblong_Medium_Pressed_Off_White', 'Envelop wit'
UNION ALL SELECT 'wedding_envelope_Oblong_Medium_Pressed_Lime', 'Envelop'
UNION ALL SELECT 'wedding_envelope_Slim_Medium_Pressed_Blue', 'Envelop'
UNION ALL SELECT 'wedding_envelope_Slim_Medium_Pressed_Lime', 'Envelop'
UNION ALL SELECT 'wedding_envelope_Slim_Medium_Light_Pink', 'Envelop licht roze'
UNION ALL SELECT 'wedding_envelope_Slim_Medium_Biotop', 'Envelop off-white'
UNION ALL SELECT 'wedding_envelope_Slim_Medium_Metallic_White', 'Envelop wit'
UNION ALL SELECT 'envelope_wedding_standard_medium_metallic_platinum_withoutwindow', 'Envelop'
UNION ALL SELECT 'wedding_envelope_Oblong_Medium_Pressed_Pink', 'Envelop'
UNION ALL SELECT 'envelope_wedding_standard_medium_roma_light_pink_withoutwindow', 'Envelop licht roze'
UNION ALL SELECT 'envelope_wedding_standard_medium_roma_bright_pink_withoutwindow', 'Envelop fuchsia'
UNION ALL SELECT 'envelope_wedding_standard_medium_roma_bright_red_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_wedding_standard_medium_roma_biotop_withoutwindow', 'Envelop off-white'
UNION ALL SELECT 'envelope_wedding_standard_medium_roma_ocean_blue_withoutwindow', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_wedding_standard_medium_roma_apple_green_withoutwindow', 'Envelop groen'
UNION ALL SELECT 'wedding_envelope_Slim_Medium_Metallic_Platinum', 'Envelop'
UNION ALL SELECT 'wedding_envelope_Slim_Medium_Pressed_Pink', 'Envelop'
UNION ALL SELECT 'wedding_envelope_Slim_Medium_Pressed_Orange', 'Envelop'
UNION ALL SELECT 'wedding_envelope_Slim_Medium_Bright_Orange', 'Envelop'
UNION ALL SELECT 'wedding_envelope_Slim_Medium_Pressed_Off_White', 'Envelop wit'
UNION ALL SELECT 'envelope_invitation_square_large_roma_ocean_blue_windowed', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_invitation_square_large_roma_bright_pink_windowed', 'Envelop fuchsia'
UNION ALL SELECT 'envelope_invitation_square_large_roma_bright_red_windowed', 'Envelop'
UNION ALL SELECT 'envelope_invitation_square_large_fizz_lime_windowed', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_invitation_square_large_roma_biotop_windowed', 'Envelop off-white'
UNION ALL SELECT 'envelope_invitation_square_supersize_fizz_black_windowed', 'Envelop echt zwart'
UNION ALL SELECT 'envelope_invitation_square_supersize_fizz_blue_windowed', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_invitation_square_supersize_fizz_bright_pink_windowed', 'Envelop knal roze'
UNION ALL SELECT 'envelope_invitation_square_supersize_fizz_bright_yellow_windowed', 'Envelop vrolijk geel'
UNION ALL SELECT 'envelope_invitation_square_supersize_fizz_dark_orange_windowed', 'Envelop fris oranje'
UNION ALL SELECT 'envelope_invitation_square_supersize_fizz_dark_purple_windowed', 'Envelop chique paarse'
UNION ALL SELECT 'envelope_invitation_square_supersize_fizz_dark_red_windowed', 'Envelop diep rood'
UNION ALL SELECT 'envelope_invitation_square_supersize_fizz_grey_windowed', 'Envelop stijlvol grijs'
UNION ALL SELECT 'envelope_invitation_square_supersize_fizz_lime_windowed', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_invitation_square_supersize_fizz_white_windowed', 'Envelop helder wit'
UNION ALL SELECT 'envelope_invitation_square_xxl_fizz_black_windowed', 'Envelop echt zwart'
UNION ALL SELECT 'envelope_invitation_square_xxl_fizz_blue_windowed', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_invitation_square_xxl_fizz_bright_pink_windowed', 'Envelop knal roze'
UNION ALL SELECT 'envelope_invitation_square_xxl_fizz_bright_yellow_windowed', 'Envelop vrolijk geel'
UNION ALL SELECT 'envelope_invitation_square_xxl_fizz_dark_orange_windowed', 'Envelop fris oranje'
UNION ALL SELECT 'envelope_invitation_square_xxl_fizz_dark_purple_windowed', 'Envelop chique paarse'
UNION ALL SELECT 'envelope_invitation_square_xxl_fizz_dark_red_windowed', 'Envelop diep rood'
UNION ALL SELECT 'envelope_invitation_square_xxl_fizz_grey_windowed', 'Envelop stijlvol grijs'
UNION ALL SELECT 'envelope_invitation_square_xxl_fizz_lime_windowed', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_invitation_square_xxl_fizz_white_windowed', 'Envelop helder wit'
UNION ALL SELECT 'envelope_invitation_standard_medium_roma_ocean_blue_windowed', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_invitation_standard_medium_roma_bright_pink_windowed', 'Envelop fuchsia'
UNION ALL SELECT 'envelope_invitation_standard_medium_roma_bright_red_windowed', 'Envelop'
UNION ALL SELECT 'envelope_invitation_standard_medium_fizz_lime_windowed', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_invitation_standard_medium_roma_biotop_windowed', 'Envelop off-white'
UNION ALL SELECT 'envelope_invitation_standard_supersize_fizz_black_windowed', 'Envelop echt zwart'
UNION ALL SELECT 'envelope_invitation_standard_supersize_fizz_blue_windowed', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_invitation_standard_supersize_fizz_bright_pink_windowed', 'Envelop knal roze'
UNION ALL SELECT 'envelope_invitation_standard_supersize_fizz_bright_yellow_windowed', 'Envelop vrolijk geel'
UNION ALL SELECT 'envelope_invitation_standard_supersize_fizz_dark_orange_windowed', 'Envelop fris oranje'
UNION ALL SELECT 'envelope_invitation_standard_supersize_fizz_dark_purple_windowed', 'Envelop chique paarse'
UNION ALL SELECT 'envelope_invitation_standard_supersize_fizz_dark_red_windowed', 'Envelop diep rood'
UNION ALL SELECT 'envelope_invitation_standard_supersize_fizz_grey_windowed', 'Envelop stijlvol grijs'
UNION ALL SELECT 'envelope_invitation_standard_supersize_fizz_lime_windowed', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_invitation_standard_supersize_fizz_white_windowed', 'Envelop helder wit'
UNION ALL SELECT 'envelope_invitation_standard_xxl_fizz_lime_windowed', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_invitation_standard_xxl_fizz_black_windowed', 'Envelop echt zwart'
UNION ALL SELECT 'envelope_invitation_standard_xxl_fizz_blue_windowed', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_invitation_standard_xxl_fizz_bright_pink_windowed', 'Envelop knal roze'
UNION ALL SELECT 'envelope_invitation_standard_xxl_fizz_bright_yellow_windowed', 'Envelop vrolijk geel'
UNION ALL SELECT 'envelope_invitation_standard_xxl_fizz_dark_orange_windowed', 'Envelop fris oranje'
UNION ALL SELECT 'envelope_invitation_standard_xxl_fizz_dark_purple_windowed', 'Envelop chique paarse'
UNION ALL SELECT 'envelope_invitation_standard_xxl_fizz_dark_red_windowed', 'Envelop diep rood'
UNION ALL SELECT 'envelope_invitation_standard_xxl_fizz_grey_windowed', 'Envelop stijlvol grijs'
UNION ALL SELECT 'envelope_invitation_standard_xxl_fizz_white_windowed', 'Envelop helder wit'
UNION ALL SELECT 'envelope_invitation_standard_medium_paperlynx_silver_windowed', 'Envelop'
UNION ALL SELECT 'envelope_invitation_standard_medium_paperlynx_gold_windowed', 'Envelop'
UNION ALL SELECT 'envelope_invitation_square_large_paperlynx_silver_windowed', 'Envelop'
UNION ALL SELECT 'envelope_invitation_square_large_paperlynx_gold_windowed', 'Envelop'
UNION ALL SELECT 'envelope_invitation_square_large_roma_ocean_blue_withoutwindow', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_invitation_square_large_roma_light_pink_withoutwindow', 'Envelop licht roze'
UNION ALL SELECT 'envelope_invitation_square_large_roma_bright_pink_withoutwindow', 'Envelop fuchsia'
UNION ALL SELECT 'envelope_invitation_square_large_roma_bright_red_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_invitation_square_large_roma_biotop_withoutwindow', 'Envelop off-white'
UNION ALL SELECT 'envelope_invitation_square_large_roma_light_blue_withoutwindow', 'Envelop licht blauw'
UNION ALL SELECT 'envelope_invitation_square_large_roma_bright_orange_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_invitation_square_large_roma_apple_green_withoutwindow', 'Envelop groen'
UNION ALL SELECT 'envelope_invitation_standard_medium_roma_bright_orange_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_invitation_standard_medium_roma_bright_pink_withoutwindow', 'Envelop fuchsia'
UNION ALL SELECT 'envelope_invitation_standard_medium_roma_biotop_withoutwindow', 'Envelop off-white'
UNION ALL SELECT 'envelope_invitation_standard_medium_roma_light_pink_withoutwindow', 'Envelop licht roze'
UNION ALL SELECT 'envelope_invitation_standard_medium_roma_light_blue_withoutwindow', 'Envelop licht blauw'
UNION ALL SELECT 'envelope_invitation_standard_medium_roma_apple_green_withoutwindow', 'Envelop groen'
UNION ALL SELECT 'envelope_invitation_standard_medium_roma_bright_red_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_invitation_standard_medium_roma_ocean_blue_withoutwindow', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_invitation_square_large_paperlynx_silver_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_invitation_square_large_paperlynx_gold_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_invitation_standard_medium_paperlynx_silver_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_invitation_standard_medium_paperlynx_gold_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_evd_square_supersize_paperlynx_gold_windowed', 'Envelop'
UNION ALL SELECT 'envelope_evd_square_xxl_paperlynx_gold_windowed', 'Envelop'
UNION ALL SELECT 'envelope_evd_standard_supersize_paperlynx_gold_windowed', 'Envelop'
UNION ALL SELECT 'envelope_evd_standard_xxl_paperlynx_gold_windowed', 'Envelop'
UNION ALL SELECT 'envelope_evd_square_supersize_paperlynx_silver_windowed', 'Envelop'
UNION ALL SELECT 'envelope_evd_square_xxl_paperlynx_silver_windowed', 'Envelop'
UNION ALL SELECT 'envelope_evd_standard_supersize_paperlynx_silver_windowed', 'Envelop'
UNION ALL SELECT 'envelope_evd_standard_xxl_paperlynx_silver_windowed', 'Envelop'
UNION ALL SELECT 'envelope_evd_square_supersize_paperlynx_gold_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_evd_square_xxl_paperlynx_gold_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_evd_standard_supersize_paperlynx_gold_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_evd_standard_xxl_paperlynx_gold_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_evd_square_supersize_paperlynx_silver_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_evd_standard_xxl_paperlynx_silver_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_evd_square_xxl_paperlynx_silver_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_evd_standard_supersize_paperlynx_silver_withoutwindow', 'Envelop'
UNION ALL SELECT 'envelope_invitation_standard_medium_fizz_lime_withoutwindow', 'Envelop Greetz groen'
UNION ALL SELECT 'envelopeevdstandardmediumfizzlimewindowed', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_invitation_square_large_fizz_blue_windowed', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_invitation_square_large_fizz_blue_withoutwindow', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_invitation_square_large_fizz_lime_withoutwindow', 'Envelop Greetz groen'
UNION ALL SELECT 'envelope_invitation_square_large_fizz_dark_red_windowed', 'Envelop diep rood'
UNION ALL SELECT 'envelope_invitation_square_large_fizz_dark_red_withoutwindow', 'Envelop diep rood'
UNION ALL SELECT 'envelope_invitation_square_large_fizz_bright_pink_windowed', 'Envelop knal roze'
UNION ALL SELECT 'envelope_invitation_square_large_fizz_bright_pink_withoutwindow', 'Envelop knal roze'
UNION ALL SELECT 'envelope_invitation_square_large_fizz_white_windowed', 'Envelop helder wit'
UNION ALL SELECT 'envelope_invitation_square_large_fizz_white_withoutwindow', 'Envelop helder wit'
UNION ALL SELECT 'envelope_invitation_standard_medium_fizz_white_windowed', 'Envelop helder wit'
UNION ALL SELECT 'envelope_invitation_standard_medium_Fizz_white_withoutwindow', 'Envelop helder wit'
UNION ALL SELECT 'envelope_invitation_standard_medium_fizz_dark_red_windowed', 'Envelop diep rood'
UNION ALL SELECT 'envelope_invitation_standard_medium_fizz_dark_red_withoutwindow', 'Envelop diep rood'
UNION ALL SELECT 'envelope_invitation_standard_medium_fizz_Bright_Pink_windowed', 'Envelop knal roze'
UNION ALL SELECT 'envelope_invitation_standard_medium_fizz_Bright_Pink_withoutwindow', 'Envelop knal roze'
UNION ALL SELECT 'envelope_invitation_standard_medium_fizz_Blue_windowed', 'Envelop oceaan blauw'
UNION ALL SELECT 'envelope_invitation_standard_medium_fizz_Blue_withoutwindow', 'Envelop oceaan blauw'
UNION ALL SELECT 'AdditionalEnvelope_Standard_Medium_Fizz_White', 'Envelop helder wit'
UNION ALL SELECT 'AdditionalEnvelope_Standard_XL_Fizz_White', 'Envelop helder wit'
UNION ALL SELECT 'AdditionalEnvelope_Standard_Supersize_Fizz_White', 'Envelop helder wit'
UNION ALL SELECT 'additionalEnvelope_Square_Large', 'Envelop Greetz groen'
UNION ALL SELECT 'AdditionalEnvelope_Square_XXL_Fizz_White', 'Envelop helder wit'
UNION ALL SELECT 'AdditionalEnvelope_Square_Supersize_Fizz_White', 'Envelop helder wit'
UNION ALL SELECT 'additionalEnvelope_Square_Large_Blue', 'Envelop'
UNION ALL SELECT 'additionalEnvelope_Square_Large_Pink', 'Envelop'
UNION ALL SELECT 'additionalEnvelope_Square_Large_White_Gloss', 'Envelop'
UNION ALL SELECT 'additionalEnvelope_Square_Large_Ivory', 'Envelop'
UNION ALL SELECT 'additionalEnvelope_Square_Large_White_Linen', 'Envelop'
UNION ALL SELECT 'additionalEnvelope_Square_Large_White_Laid', 'Envelop'
UNION ALL SELECT 'AdditionalEnvelope_Square_Large_Fizz_White', 'Envelop helder wit'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Large_Metallic_White', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Large_Metallic_Platinum', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Large_Pressed_Off_White', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Large_Pressed_Blue', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Large_Pressed_Pink', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Large_Pressed_Red', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Large_Pressed_Lime', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Large_Pressed_Orange', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Large_Light_Blue', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Large_Light_Pink', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Large_Bright_Pink', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Large_Bright_Orange', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Large_Bright_Red', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Large_Biotop', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Large_Ocean_Blue', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Large_Apple_Green', 'Envelop'
UNION ALL SELECT 'AdditionalEnvelope_Standard_Medium_Fizz_Lime', 'Envelop Greetz groen'
UNION ALL SELECT 'AdditionalEnvelope_Standard_XXL_Fizz_Lime', 'Envelop Greetz groen'
UNION ALL SELECT 'AdditionalEnvelope_Standard_XXL_Fizz_Bright_Pink', 'Envelop fuchsia'
UNION ALL SELECT 'AdditionalEnvelope_Standard_XXL_Fizz_Blue', 'Envelop oceaan blauw'
UNION ALL SELECT 'AdditionalEnvelope_Standard_XXL_Fizz_Dark_Red', 'Envelop diep rood'
UNION ALL SELECT 'AdditionalEnvelope_Standard_XXL_Fizz_Dark_Orange', 'Envelop fris oranje'
UNION ALL SELECT 'AdditionalEnvelope_Standard_XXL_Fizz_Bright_Yellow', 'Envelop vrolijk geel'
UNION ALL SELECT 'AdditionalEnvelope_Standard_XXL_Fizz_Dark_Purple', 'Envelop chique paarse'
UNION ALL SELECT 'AdditionalEnvelope_Standard_XXL_Fizz_Grey', 'Envelop stijlvol grijs'
UNION ALL SELECT 'AdditionalEnvelope_Standard_XXL_Fizz_Black', 'Envelop echt zwart'
UNION ALL SELECT 'AdditionalEnvelope_Standard_Supersize_Fizz_Lime', 'Envelop Greetz groen'
UNION ALL SELECT 'AdditionalEnvelope_Standard_Supersize_Fizz_Bright_Pink', 'Envelop fuchsia'
UNION ALL SELECT 'AdditionalEnvelope_Standard_Supersize_Fizz_Blue', 'Envelop oceaan blauw'
UNION ALL SELECT 'AdditionalEnvelope_Standard_Supersize_Fizz_Dark_Red', 'Envelop diep rood'
UNION ALL SELECT 'AdditionalEnvelope_Standard_Supersize_Fizz_Dark_Orange', 'Envelop fris oranje'
UNION ALL SELECT 'AdditionalEnvelope_Standard_Supersize_Fizz_Bright_Yellow', 'Envelop vrolijk geel'
UNION ALL SELECT 'AdditionalEnvelope_Standard_Supersize_Fizz_Dark_Purple', 'Envelop chique paarse'
UNION ALL SELECT 'AdditionalEnvelope_Standard_Supersize_Fizz_Grey', 'Envelop stijlvol grijs'
UNION ALL SELECT 'AdditionalEnvelope_Standard_Supersize_Fizz_Black', 'Envelop echt zwart'
UNION ALL SELECT 'AdditionalEnvelope_Square_Large_Fizz_Lime', 'Envelop Greetz groen'
UNION ALL SELECT 'AdditionalEnvelope_Square_XXL_Fizz_Lime', 'Envelop Greetz groen'
UNION ALL SELECT 'AdditionalEnvelope_Square_XXL_Fizz_Bright_Pink', 'Envelop fuchsia'
UNION ALL SELECT 'AdditionalEnvelope_Square_XXL_Fizz_Blue', 'Envelop oceaan blauw'
UNION ALL SELECT 'AdditionalEnvelope_Square_XXL_Fizz_Dark_Red', 'Envelop diep rood'
UNION ALL SELECT 'AdditionalEnvelope_Square_XXL_Fizz_Dark_Orange', 'Envelop fris oranje'
UNION ALL SELECT 'AdditionalEnvelope_Square_XXL_Fizz_Bright_Yellow', 'Envelop vrolijk geel'
UNION ALL SELECT 'AdditionalEnvelope_Square_XXL_Fizz_Dark_Purple', 'Envelop chique paarse'
UNION ALL SELECT 'AdditionalEnvelope_Square_XXL_Fizz_Grey', 'Envelop stijlvol grijs'
UNION ALL SELECT 'AdditionalEnvelope_Square_XXL_Fizz_Black', 'Envelop echt zwart'
UNION ALL SELECT 'AdditionalEnvelope_Square_Supersize_Fizz_Lime', 'Envelop Greetz groen'
UNION ALL SELECT 'AdditionalEnvelope_Square_Supersize_Fizz_Bright_Pink', 'Envelop fuchsia'
UNION ALL SELECT 'AdditionalEnvelope_Square_Supersize_Fizz_Blue', 'Envelop oceaan blauw'
UNION ALL SELECT 'AdditionalEnvelope_Square_Supersize_Fizz_Dark_Red', 'Envelop diep rood'
UNION ALL SELECT 'AdditionalEnvelope_Square_Supersize_Fizz_Dark_Orange', 'Envelop fris oranje'
UNION ALL SELECT 'AdditionalEnvelope_Square_Supersize_Fizz_Bright_Yellow', 'Envelop vrolijk geel'
UNION ALL SELECT 'AdditionalEnvelope_Square_Supersize_Fizz_Dark_Purple', 'Envelop chique paarse'
UNION ALL SELECT 'AdditionalEnvelope_Square_Supersize_Fizz_Grey', 'Envelop stijlvol grijs'
UNION ALL SELECT 'AdditionalEnvelope_Square_Supersize_Fizz_Black', 'Envelop echt zwart'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Small_Metallic_Platinum', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Small_Pressed_Blue', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Small_Pressed_Lime', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Small_Bright_Pink', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Small_Biotop', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Medium_Light_Pink', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Medium_Bright_Orange', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Medium_Apple_Green', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Small_Pressed_Red', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Medium_Pressed_Pink', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Medium_Bright_Red', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Medium_Biotop', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Small_Pressed_Pink', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Small_Pressed_Red', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Small_Light_Blue', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Small_Pressed_Lime', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Small_Pressed_Orange', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Medium_Pressed_Blue', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Small_Pressed_Blue', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Small_Metallic_White', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Small_Pressed_Pink', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Small_Pressed_Red', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Small_Pressed_Orange', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Small_Light_Pink', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Small_Bright_Red', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Small_Apple_Green', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Medium_Metallic_Platinum', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Medium_Pressed_Blue', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Medium_Pressed_Pink', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Medium_Pressed_Lime', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Medium_Biotop', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Small_Metallic_Platinum', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Small_Light_Blue', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Small_Light_Pink', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Small_Bright_Orange', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Small_Biotop', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Small_Ocean_Blue', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Small_Apple_Green', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Medium_Metallic_White', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Medium_Metallic_Platinum', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Medium_Pressed_Lime', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Medium_Light_Blue', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Medium_Light_Pink', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Medium_Bright_Pink', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Medium_Apple_Green', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Small_Metallic_White', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Small_Metallic_Platinum', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Small_Pressed_Off_White', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Small_Pressed_Lime', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Small_Pressed_Orange', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Small_Light_Pink', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Small_Bright_Pink', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Small_Biotop', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Small_Ocean_Blue', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Small_Pressed_Off_White', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Small_Light_Blue', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Small_Bright_Orange', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Square_Small_Ocean_Blue', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Medium_Metallic_White', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Medium_Pressed_Off_White', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Medium_Pressed_Red', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Medium_Pressed_Orange', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Medium_Light_Blue', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Medium_Bright_Pink', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Medium_Bright_Red', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Medium_Ocean_Blue', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Small_Metallic_White', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Small_Pressed_Off_White', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Small_Pressed_Blue', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Small_Pressed_Pink', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Small_Bright_Pink', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Oblong_Small_Bright_Red', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Medium_Pressed_Off_White', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Medium_Pressed_Red', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Medium_Pressed_Orange', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Medium_Bright_Orange', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Medium_Ocean_Blue', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Small_Bright_Orange', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Small_Bright_Red', 'Envelop'
UNION ALL SELECT 'birth_additionalEnvelope_Slim_Small_Apple_Green', 'Envelop'
UNION ALL SELECT 'AdditionalEnvelope_Standard_Medium_Fizz_Bright_Pink', 'Envelop fuchsia'
UNION ALL SELECT 'AdditionalEnvelope_Standard_Medium_Fizz_Blue', 'Envelop oceaan blauw'
UNION ALL SELECT 'AdditionalEnvelope_Standard_Medium_Fizz_Dark_Red', 'Envelop diep rood'
UNION ALL SELECT 'AdditionalEnvelope_Square_Large_Fizz_Bright_Pink', 'Envelop fuchsia'
UNION ALL SELECT 'AdditionalEnvelope_Square_Large_Fizz_Blue', 'Envelop oceaan blauw'
UNION ALL SELECT 'AdditionalEnvelope_Square_Large_Fizz_Dark_Red', 'Envelop diep rood'
UNION ALL SELECT 'AdditionalEnvelope_Standard_Medium_Paperlynx_Gold', 'Paperlynx_Gold'
UNION ALL SELECT 'AdditionalEnvelope_Square_Large_Paperlynx_Gold', 'Envelop goud'
UNION ALL SELECT 'AdditionalEnvelope_Standard_Medium_Paperlynx_Silver', 'Envelop zilver'
UNION ALL SELECT 'AdditionalEnvelope_Square_Large_Paperlynx_Silver', 'Envelop zilver'
UNION ALL SELECT 'wedding_additionalEnvelope_Square_Large_Metallic_White', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Square_Large_Metallic_Platinum', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Square_Large_Pressed_Off_White', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Square_Large_Pressed_Blue', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Square_Large_Pressed_Pink', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Square_Large_Pressed_Red', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Square_Large_Pressed_Lime', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Square_Large_Pressed_Orange', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Square_Large_Light_Blue', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Square_Large_Light_Pink', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Square_Large_Bright_Pink', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Square_Large_Bright_Orange', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Square_Large_Bright_Red', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Square_Large_Biotop', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Square_Large_Ocean_Blue', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Square_Large_Apple_Green', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Oblong_Medium_Bright_Orange', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Oblong_Medium_Light_Pink', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Oblong_Medium_Apple_Green', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Oblong_Small_Pressed_Red', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Slim_Medium_Pressed_Pink', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Slim_Medium_Bright_Red', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Slim_Medium_Biotop', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Slim_Medium_Pressed_Blue', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Oblong_Medium_Metallic_Platinum', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Oblong_Medium_Pressed_Blue', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Oblong_Medium_Pressed_Pink', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Oblong_Medium_Pressed_Lime', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Oblong_Medium_Biotop', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Slim_Medium_Metallic_White', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Slim_Medium_Metallic_Platinum', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Slim_Medium_Pressed_Lime', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Slim_Medium_Light_Blue', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Slim_Medium_Light_Pink', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Slim_Medium_Bright_Pink', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Slim_Medium_Apple_Green', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Oblong_Medium_Metallic_White', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Oblong_Medium_Pressed_Off_White', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Oblong_Medium_Pressed_Red', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Oblong_Medium_Pressed_Orange', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Oblong_Medium_Light_Blue', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Oblong_Medium_Bright_Pink', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Oblong_Medium_Bright_Red', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Oblong_Medium_Ocean_Blue', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Slim_Medium_Pressed_Off_White', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Slim_Medium_Pressed_Red', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Slim_Medium_Pressed_Orange', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Slim_Medium_Bright_Orange', 'Envelop'
UNION ALL SELECT 'wedding_additionalEnvelope_Slim_Medium_Ocean_Blue', 'Envelop'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_Large_Fizz_White', 'Envelop helder wit'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_Supersize_Fizz_White', 'Envelop helder wit'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_XXL_Fizz_White', 'Envelop helder wit'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_Medium_Fizz_White', 'Envelop helder wit'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_Supersize_Fizz_White', 'Envelop helder wit'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_XL_Fizz_White', 'Envelop helder wit'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_Large_Fizz_Blue', 'Envelop oceaan blauw'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_Large_Fizz_Bright_Pink', 'Envelop fuchsia'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_Large_Fizz_Dark_Red', 'Envelop diep rood'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_Large_Fizz_Lime', 'Envelop Greetz groen'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_Large_Paperlynx_Gold', 'Envelop goud'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_Large_Paperlynx_Silver', 'Envelop zilver'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_Supersize_Fizz_Black', 'Envelop echt zwart'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_Supersize_Fizz_Blue', 'Envelop oceaan blauw'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_Supersize_Fizz_Bright_Pink', 'Envelop fuchsia'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_Supersize_Fizz_Bright_Yellow', 'Envelop vrolijk geel'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_Supersize_Fizz_Dark_Orange', 'Envelop fris oranje'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_Supersize_Fizz_Dark_Purple', 'Envelop chique paarse'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_Supersize_Fizz_Dark_Red', 'Envelop diep rood'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_Supersize_Fizz_Grey', 'Envelop stijlvol grijs'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_Supersize_Fizz_Lime', 'Envelop Greetz groen'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_XXL_Fizz_Black', 'Envelop echt zwart'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_XXL_Fizz_Blue', 'Envelop oceaan blauw'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_XXL_Fizz_Bright_Pink', 'Envelop fuchsia'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_XXL_Fizz_Bright_Yellow', 'Envelop vrolijk geel'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_XXL_Fizz_Dark_Orange', 'Envelop fris oranje'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_XXL_Fizz_Dark_Purple', 'Envelop chique paarse'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_XXL_Fizz_Dark_Red', 'Envelop diep rood'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_XXL_Fizz_Grey', 'Envelop stijlvol grijs'
UNION ALL SELECT 'invite_AdditionalEnvelope_Square_XXL_Fizz_Lime', 'Envelop Greetz groen'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_Medium_Fizz_Lime', 'Envelop Greetz groen'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_Medium_Paperlynx_Gold', 'Envelop goud'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_Medium_Paperlynx_Silver', 'Envelop zilver'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_Supersize_Fizz_Black', 'Envelop echt zwart'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_Supersize_Fizz_Blue', 'Envelop oceaan blauw'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_Supersize_Fizz_Bright_Pink', 'Envelop fuchsia'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_Supersize_Fizz_Bright_Yellow', 'Envelop vrolijk geel'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_Supersize_Fizz_Dark_Orange', 'Envelop fris oranje'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_Supersize_Fizz_Dark_Purple', 'Envelop chique paarse'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_Supersize_Fizz_Dark_Red', 'Envelop diep rood'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_Supersize_Fizz_Grey', 'Envelop stijlvol grijs'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_Supersize_Fizz_Lime', 'Envelop Greetz groen'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_XXL_Fizz_Black', 'Envelop echt zwart'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_XXL_Fizz_Blue', 'Envelop oceaan blauw'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_XXL_Fizz_Bright_Pink', 'Envelop fuchsia'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_XXL_Fizz_Bright_Yellow', 'Envelop vrolijk geel'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_XXL_Fizz_Dark_Orange', 'Envelop fris oranje'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_XXL_Fizz_Dark_Purple', 'Envelop chique paarse'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_XXL_Fizz_Dark_Red', 'Envelop diep rood'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_XXL_Fizz_Grey', 'Envelop stijlvol grijs'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_XXL_Fizz_Lime', 'Envelop Greetz groen'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_Medium_Fizz_Blue', 'Envelop oceaan blauw'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_Medium_Fizz_Bright_Pink', 'Envelop fuchsia'
UNION ALL SELECT 'invite_AdditionalEnvelope_Standard_Medium_Fizz_Dark_Red', 'Envelop diep rood'
UNION ALL SELECT 'invite_additionalEnvelope_Standard_Medium_Biotop', 'Envelop'
UNION ALL SELECT 'invite_additionalEnvelope_Standard_Medium_Apple_Green', 'Envelop'
UNION ALL SELECT 'invite_additionalEnvelope_Standard_Medium_Ocean_Blue', 'Envelop'
UNION ALL SELECT 'invite_additionalEnvelope_Standard_Medium_Bright_Pink', 'Envelop'
UNION ALL SELECT 'invite_additionalEnvelope_Standard_Medium_Light_Blue', 'Envelop'
UNION ALL SELECT 'invite_additionalEnvelope_Standard_Medium_Bright_Orange', 'Envelop'
UNION ALL SELECT 'invite_additionalEnvelope_Standard_Medium_Light_Pink', 'Envelop'
UNION ALL SELECT 'invite_additionalEnvelope_Standard_Medium_Bright_Red', 'Envelop'
UNION ALL SELECT 'invite_additionalEnvelope_Square_Large_Biotop', 'Envelop'
UNION ALL SELECT 'invite_additionalEnvelope_Square_Large_Light_Pink', 'Envelop'
UNION ALL SELECT 'invite_additionalEnvelope_Square_Large_Light_Blue', 'Envelop'
UNION ALL SELECT 'invite_additionalEnvelope_Square_Large_Ocean_Blue', 'Envelop'
UNION ALL SELECT 'invite_additionalEnvelope_Square_Large_Bright_Red', 'Envelop'
UNION ALL SELECT 'invite_additionalEnvelope_Square_Large_Bright_Orange', 'Envelop'
UNION ALL SELECT 'invite_additionalEnvelope_Square_Large_Bright_Pink', 'Envelop'
UNION ALL SELECT 'invite_additionalEnvelope_Square_Large_Apple_Green', 'Envelop'
UNION ALL SELECT 'AdditionalEnvelope_Standard_XXL_Paperlynx_Silver', 'Envelop goud'
UNION ALL SELECT 'AdditionalEnvelope_Standard_XXL_Fizz_Silver', 'Envelop zilver'
UNION ALL SELECT 'AdditionalEnvelope_Standard_Supersize_Fizz_Silver', 'Envelop zilver'
UNION ALL SELECT 'AdditionalEnvelope_Square_XXL_Fizz_Silver', 'Envelop zilver'
UNION ALL SELECT 'AdditionalEnvelope_Square_Supersize_Fizz_Silver', 'Envelop zilver'
UNION ALL SELECT 'AdditionalEnvelope_Standard_XXL_Fizz_Gold', 'Envelop goud'
UNION ALL SELECT 'AdditionalEnvelope_Standard_Supersize_Fizz_Gold', 'Envelop goud'
UNION ALL SELECT 'AdditionalEnvelope_Square_XXL_Fizz_Gold', 'Envelop goud'
UNION ALL SELECT 'AdditionalEnvelope_Square_Supersize_Fizz_Gold', 'Envelop goud'
;