CREATE OR REPLACE TABLE "PROD"."WORKSPACE_GREETZ_HISTORY_MIGRATION"."DIFF_ESIV" AS (
SELECT od.order_id, SUM(od.item_esev) as item_esev , AVG(os.ORDER_ESEV) as ORDER_ESEV -- AVG(ORDER_ISIV)
, SUM(od.item_ISIV) as item_ISIV, AVG(os.ORDER_ISIV) as ORDER_ISIV
, SUM(od.item_ISEV) as item_ISEV, AVG(os.ORDER_ISEV) as ORDER_ISEV
, SUM(od.item_esiv) as item_esiv, AVG(os.ORDER_ESIV) as ORDER_ESIV
FROM  "PROD"."WORKSPACE_GREETZ_HISTORY_MIGRATION"."RAW_GREETZ_CT_ORDER_ITEMS_DETAILED_BACKFILL" od
    join  "PROD"."WORKSPACE_GREETZ_HISTORY_MIGRATION"."RAW_GREETZ_CT_ORDERS_STAGING_BACKFILL" os
        ON od.ORDER_ID = os.ORDER_ID
GROUP BY 1
having abs(SUM(od.item_isiv) -  AVG(os.ORDER_ISIV)) > 0.00001
or  abs(SUM(od.item_isev) - AVG(os.ORDER_ISEV)) > 0.00001
or  abs(SUM(od.item_esiv) - AVG(os.ORDER_ESIV)) > 0.00001
or  abs(SUM(od.item_esev) - AVG(os.ORDER_ESEV)) > 0.00001
  )
;
-- 42846

/*SELECT od.order_id, SUM(od.item_esev) , AVG(os.ORDER_ESEV) -- AVG(ORDER_ISIV)
, SUM(od.item_ISIV) , AVG(os.ORDER_ISIV)
, SUM(od.item_ISEV) , AVG(os.ORDER_ISEV)
, SUM(od.item_esiv) , AVG(os.ORDER_ESIV)
FROM  "PROD"."WORKSPACE_GREETZ_HISTORY_MIGRATION"."TMP_RAW_GREETZ_CT_ORDER_ITEMS_DETAILED_BACKFILL_2" od
    join  "PROD"."WORKSPACE_GREETZ_HISTORY_MIGRATION"."TMP_RAW_GREETZ_CT_ORDERS_STAGING_BACKFILL" os
        ON od.ORDER_ID = os.ORDER_ID
GROUP BY 1
having abs(SUM(od.item_isiv) -  AVG(os.ORDER_ISIV)) < 0.00001
and  abs(SUM(od.item_isev) - AVG(os.ORDER_ISEV)) < 0.00001
and  abs(SUM(od.item_esiv) - AVG(os.ORDER_ESIV)) < 0.00001
and  abs(SUM(od.item_esev) - AVG(os.ORDER_ESEV)) < 0.00001
;

select count(*) from "PROD"."WORKSPACE_GREETZ_HISTORY_MIGRATION"."TMP_RAW_GREETZ_CT_ORDERS_STAGING_BACKFILL";
select * FROM  "PROD"."WORKSPACE_GREETZ_HISTORY_MIGRATION"."TMP_RAW_GREETZ_CT_ORDER_ITEMS_DETAILED_BACKFILL_2";
select count(*) from "PROD"."WORKSPACE_GREETZ_HISTORY_MIGRATION"."TMP_RAW_GREETZ_CT_ORDERS_STAGING_BACKFILL" ;
select count(*) FROM  "PROD"."WORKSPACE_GREETZ_HISTORY_MIGRATION"."TMP_RAW_GREETZ_CT_ORDER_ITEMS_DETAILED_BACKFILL";

select * FROM  "PROD"."WORKSPACE_GREETZ_HISTORY_MIGRATION"."TMP_RAW_GREETZ_CT_ORDER_ITEMS_DETAILED_BACKFILL" where order_id = 1154749368;

select * FROM "PROD"."WORKSPACE_GREETZ_HISTORY_MIGRATION"."TMP_DIFF_ESIV_2"; -- 1783
select * FROM "PROD"."WORKSPACE_GREETZ_HISTORY_MIGRATION"."TMP_DIFF_ESIV_3"; -- 19*/

